[machine]
name    = ALF TV Game
family  = console
hw      = ALF
memory  = 64
cpu.frq = 3500000

[video]
geometry = ULA.48

[sound]
psg.count = 0

[rom]
# One 32K dump: the games menu in bank 0, Sinclair BASIC 48 in bank 1
banks = 2
rom0 = alf.rom
