[machine]
name      = ATM Turbo 2+
family    = clone
hw        = ATM2
builtin   = disk ide
memory    = 1024
cpu.frq   = 3500000
cpu.turbo = 1,2

[video]
geometry = ULA.ATM2
floatbus = attr

[sound]
psg.type   = ym
psg.stereo = abc
soundrive  = covox

[storage]
disk = trdos
ide  = atm

[input]
mouse       = yes
joy.buttons = yes

[rom]
rom0 = atm2.rom
gs   = gs105b.rom
font = sgen.rom
