[machine]
name      = Profi v5
inherit   = profi3
hw        = Profi
builtin   = disk ide
memory    = 1024

[video]
geometry = ULA.Profi5
DDpal    = yes

[sound]
psg.type = ym

[storage]
ide = profi

[rom]
rom0 = profi-bios20.rom
