[machine]
name      = Profi v3
family    = clone
hw        = Profi3
builtin   = disk
memory    = 512
reset     = shadow
cpu.frq   = 3500000
cpu.turbo = 1,2

[video]
geometry = ULA.Profi
floatbus = none

[sound]
psg.type   = ay
psg.stereo = acb
soundrive  = covox

[storage]
disk = trdos

[input]
mouse       = yes
joy.buttons = yes

[rom]
rom0 = profi-kramis02.rom
gs   = gs105b.rom
