[machine]
name      = Scorpion ZS 256
family    = clone
hw        = Scorpion
builtin   = disk
memory    = 256
cpu.frq   = 3500000
scrp.wait = yes

[video]
geometry  = ULA.Scorpion
4t-border = yes
floatbus  = attr

[sound]
psg.type   = ay
psg.stereo = bac
soundrive  = covox

[storage]
disk = trdos

[input]
mouse = yes
joy   = kempston

[rom]
rom0 = scorpion295.rom
gs   = gs105b.rom
