[machine]
name      = Scorpion ZS 256 Turbo+
inherit   = scorp
hw        = ScorpionTP
cpu.turbo = 1,2
scrp.wait = no

[video]
geometry  = ULA.ScorpionTP

[storage]
ide = smuc

[rom]
rom0 = prof401.rom
