#include <QMatrix4x4>
#include <QCursor>
#include <QTimer>
#include <QMenu>
#include <QMenuBar>
#include <QSet>
#include <QMessageBox>
#include <QPointer>
#include <QProgressBar>
#include <QTableWidget>
#include <QTime>
#include <QDateTime>
#include <QUrl>
#include <QMimeData>
#include <QPainter>
#include <QFileDialog>
#include <QGuiApplication>
#include <QDesktopServices>
#include <QActionGroup>
#include <QLayout>
#include <QWindow>
#include <QContextMenuEvent>
#include <QShortcut>
#include <QSet>
#include <QStyleOption>
#include <QApplication>

#include <QDebug>

// QDesktopWidget removed in Qt6
#if QT_VERSION < QT_VERSION_CHECK(6,0,0)
	#include <QDesktopWidget>
#endif

#include <fstream>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>

#include "xcore/xcore.h"
#include "xcore/sound.h"
#include "xcore/autostart.h"
#include "xcore/rewind.h"
#include "xcore/fastload.h"
#include "emulwin.h"
#include "filer.h"
#include "watcher.h"
#include "xgui/favorites.h"
#include "xgui/xgui.h"
#include "xcore/pacing.h"

#include "xcore/vfilters.h"
#include "xcore/vscalers.h"
#include "xcore/vidrec.h"

#include "version.h"		// generated by CMake


#define	XPTITLE	XPRODUCT " (" XVERSION ")"
#define	FPS_TICK_MS	200		// the timer the fps readout is sampled on

// where the image named in the title is (drives are 0..3)
#define	MEDIA_TAPE	4
#define	MEDIA_SNAP	-1

#if defined(__WIN32)
#include <windows.h>
#include <winuser.h>
#endif

// mainwin

#if defined(__WIN32)
// Fullscreen is a line taller than the screen to be composed: for good without
// Low latency, else only while a menu is up (see fsCompose)
static bool fsWantTall(bool menuUp) {
	return menuUp || !conf.vid.lowLatency;
}
#endif

void MainWin::updateHead() {
	QStringList parts;
	QString media = media_current();
	if (!media.isEmpty())
		parts << QFileInfo(media).fileName();
	parts << XPTITLE;
#ifdef ISDEBUG
	parts << "debug";
#endif
	const xMachine* mac = xm_find(conf.macId);
	if (conf.zx && mac)
		parts << QString::fromLocal8Bit(mac->name.c_str());
	if (conf.emu.fast && !autostart_busy() && !fastload_busy())	// neither fast mode is the user's
		parts << "fast";
	frame->setWindowTitle(parts.join(" - "));
}

void MainWin::updateWindow() {
	block = 1;
	// the texture still holds the frame cut to the old bounds, and painting it
	// into the resized window would stretch it until the next frame arrives
	refit = 1;
	QSize wsz;
	Computer* comp = conf.zx;
	vid_set_zoom(conf.vid.scale);		// where the picture goes, and how big
	// a size change can switch the shader off or bring it back (wantedShader)
	if (conf.vid.shd_support && (wantedShader() != shdLoaded))
		loadShader();
	blockSignals(true);
	showBars();
	if (conf.vid.fullScreen) {
#if defined(__WIN32)
		fsTall = fsWantTall(fsHeld());
#endif
		wsz = SCREENSIZE + QSize(0, fsTall ? 1 : 0);
		frame->setWindowState(frame->windowState() | Qt::WindowFullScreen);
	} else {
		// the picture: a whole number of pixels per dot, or it would be
		// resampled and some columns come out a pixel wider than others
		wsz = QSize(drawW, drawH);
		// Qt 5 forgets a widget is fullscreen once it has been resized - the layout
		// does that - while its window stays so, and leaving would then do nothing,
		// title bar never coming back: the widget is told fullscreen again first.
		QWindow* win = frame->windowHandle();
		if (win && (win->windowStates() & Qt::WindowFullScreen))
			frame->setWindowState(frame->windowState() | Qt::WindowFullScreen);
		frame->setWindowState(frame->windowState() & ~Qt::WindowFullScreen);
	}
	setFixedSize(wsz);
	blockSignals(false);
	// the buffer holds the whole raster, whatever part of it is shown
	bytesPerLine = comp->vid->full.x * 8;
	bufSize = bytesPerLine * comp->vid->full.y * (comp->vid->linedbl ? 2 : 1);
	updateHead();
	block = 0;
	emit s_keywin_snap();		// a docked keyboard follows the new size
}

bool MainWin::saveChanged() {
	bool yep = true;
	QString str;
	Floppy* flp;
	for (int i = 0; (i < 4) && yep; i++) {
		flp = conf.zx->dif->flp[i];
		if (!flp->changed) continue;
		str = QString("Disk %0 was changed<br>Save it?").arg(QChar('A' + i));
		switch (askYNC(str.toLocal8Bit().data())) {
			case QMessageBox::Yes:
				yep &= save_file(conf.zx, flp->path, FG_DISK, i);
				break;
			case QMessageBox::Cancel:
				yep = false;
				break;
		}
	}
	return yep;
}

void MainWin::pause(bool p, int msk) {
	conf.emu.fast = 0;
	if (p) {
		conf.emu.pause |= msk;
	} else {
		conf.emu.pause &= ~msk;
	}
	if (!grabMice || (conf.emu.pause && grabMice)) {
		releaseMouse();
	}
	if (!conf.emu.pause) {
		if (grabMice) {
			grabMouse(QCursor(Qt::BlankCursor));
			mouseRecenter();	// the pointer went its own way while paused
		}
		mapReplayHeld(conf.gpctrl->gpada);
		mapReplayHeld(conf.gpctrl->gpadb);
	}
}

// Main window

MainWin::MainWin(QMainWindow* frm) {
	qDebug() << "constructor";

	// the window is the frame, this widget is the picture in it
	frame = frm;
	frame->setCentralWidget(this);
	frame->layout()->setSizeConstraint(QLayout::SetFixedSize);
	frame->installEventFilter(this);
#ifdef __WIN32
	// Qt on Windows hands Shift+F10 to the system menu unless a shortcut claims it;
	// this one claims it and passes it on as the key it is, F10's scan code with it
	QShortcut* sf10 = new QShortcut(QKeySequence(Qt::SHIFT | Qt::Key_F10), frame);
	sf10->setContext(Qt::WindowShortcut);
	sf10->setAutoRepeat(false);		// one press, one NMI
	connect(sf10, &QShortcut::activated, this, [this]() {
		QKeyEvent ev(QEvent::KeyPress, Qt::Key_F10, Qt::ShiftModifier, XKEY_F10, 0x79, 0);
		keyPressEvent(&ev);
	});
#endif
	frame->setWindowTitle(XPTITLE);
	setFocusPolicy(Qt::StrongFocus);
	setMouseTracking(true);
	frame->setWindowIcon(QGuiApplication::windowIcon());
	setAcceptDrops(true);
	// setAutoFillBackground(false);
	paintOwed = 0;
	conf.emu.pause = 0;
	scrCounter = 0;
	scrInterval = 0;
	grabMice = 0;
	warpTtl = 0;
	warpFail = 0;
	block = 0;
	hasPicture = 0;
	upSwaps = -1;
	refit = 0;
	mediaSrc = MEDIA_SNAP;
	mediaSeen = 0;
//	relskip = 0;

	msgTimer = 0;
	msg.clear();
	alphabet.load(":/font.png");

	shotFormat["bmp"] = SCR_BMP;
	shotFormat["png"] = SCR_PNG;
	shotFormat["jpg"] = SCR_JPG;
	shotFormat["scr"] = SCR_SCR;
	shotFormat["hobeta"] = SCR_HOB;

	leds[led_kbd].load(":/images/scanled.png");
	leds[led_joy].load(":/images/joystick.png");
	leds[led_mouse].load(":/images/mouse.png");
	leds[led_tap_red].load(":/images/tapeRed.png");
	leds[led_tap_yellow].load(":/images/tapeYellow.png");
	leds[led_disk_green].load(":/images/diskGreen.png");
	leds[led_disk_red].load(":/images/diskRed.png");
	leds[led_wav].load(":/images/wav.png");
	osdImg[osd_fast].load(":/images/osd-time-fast.png");
	osdImg[osd_rewind].load(":/images/osd-time-rewind.png");
	osdImg[osd_pause].load(":/images/osd-time-pause.png");
	osdImg[osd_rec].load(":/images/osd-rec.png");
	osdImg[osd_rec_off].load(":/images/osd-rec-off.png");
	for (int i = 0; i < 3; i++) {
		osdImg[osd_ffwd2 + i].load(QString(":/images/osd-time-ffwd%0.png").arg(2 << i));
		osdImg[osd_slow2 + i].load(QString(":/images/osd-time-slow%0.png").arg(2 << i));
	}
	for (QImage& img : osdImg)
		img.setDevicePixelRatio(2);	// drawn at half its size, sharp on a HiDPI screen

//	conf.joy.gpad->open(); // conf.joy.curName);

	connect(conf.gpctrl->gpada, SIGNAL(inputChanged(int,int,int)), this, SLOT(gpInputChanged(int,int,int)));
	connect(conf.gpctrl->gpadb, SIGNAL(inputChanged(int,int,int)), this, SLOT(gpInputChanged(int,int,int)));

	initFileDialog(this);
	initUserMenu();
	initMenuBar();
	initBars();
	setFocus();

	frm_ns = 0;
	timid = startTimer(20);		// 1/50 sec
	secid = startTimer(FPS_TICK_MS);	// 1/5 sec
	cmsid = startTimer(1000);	// 1 sec

	connect(&frm_tmr, SIGNAL(timeout()), this, SLOT(frame_timer()));
#if QT_VERSION >= QT_VERSION_CHECK(5,0,0)
	frm_tmr.setTimerType(Qt::PreciseTimer);
#endif
	frm_tmr.start(20);

	connect(userMenu, &QMenu::aboutToHide, this, &MainWin::menuHide);
	connect(qApp, &QGuiApplication::applicationStateChanged, this, [this](Qt::ApplicationState st) {
		bool away = (st != Qt::ApplicationActive);
		if (away == bool(conf.emu.pause & PR_FOCUS)) return;
		if (away && !conf.pauseInactive) return;
		pause(away, PR_FOCUS);
	});
	fillUserMenu();

#ifdef __APPLE__
	// Cocoa always gives the app a menu bar, even though this app never creates a
	// QMenuBar, and that menu already binds Cmd+Q to its own stub Quit item. Qt's
	// menu-role merging only replaces that stub with an app-supplied QuitRole action
	// when the action lives inside an actual QMenu/QMenuBar - a bare QAction on a
	// widget (tried first) never enters that tree, so the stub kept catching Cmd+Q.
	// An unparented QMenuBar becomes the app's default menu bar on macOS without
	// ever showing as an in-window menu on Windows/Linux.
	QMenuBar* macMenuBar = new QMenuBar(nullptr);
	QMenu* macAppMenu = macMenuBar->addMenu(QString());
	QAction* quitAct = macAppMenu->addAction(tr("Quit"));
	quitAct->setMenuRole(QAction::QuitRole);
	quitAct->setShortcut(QKeySequence::Quit);
	connect(quitAct, &QAction::triggered, this, &QWidget::close);
#endif

#ifdef USENETWORK
	openServer();
	connect(&srv, SIGNAL(newConnection()),this, SLOT(connected()));
#endif

#if defined(USEOPENGL) && !BLOCKGL
	// initializeGL creates the shaders, and it only runs when the window is
	// first shown. Exiting before that - "xpeccy-plus --help" does - would
	// otherwise leave the destructor deleting an uninitialized pointer.
	vtx_shd = NULL;
	frg_shd = NULL;
#endif

// a legacygl code must be here, else the main process doesn't finish properly (???)
#if USELEGACYGL
	QGLFormat frmt;
	frmt.setDoubleBuffer(false);
	cont = new QGLContext(frmt);
	setContext(cont);
	setAutoBufferSwap(true);
	makeCurrent();
	curtex = 0;
	shd_support = QGLShader::hasOpenGLShaders(QGLShader::Vertex) && QGLShader::hasOpenGLShaders(QGLShader::Fragment);
	qDebug() << "vtx_shd";
	vtx_shd = new QGLShader(QGLShader::Vertex, cont);
	qDebug() << "frg_shd";
	frg_shd = new QGLShader(QGLShader::Fragment, cont);
#endif

	qDebug() << "end:constructor";
}

MainWin::~MainWin() {
#if defined(USEOPENGL) && !BLOCKGL
	cleanupGL();
	delete(vtx_shd);
	delete(frg_shd);
#endif
}

// gamepad mapper
// xJoyMapEntry::key is XKEY_*

// A bound key is a host key: the hotkey it means, as on the keyboard, or -1.
// Splits the i-th key of the sequence on the way.
int MainWin::mapHotkey(const QKeySequence& seq, int i, Qt::Key* key, Qt::KeyboardModifier* mod) {
	*key = Qt::Key(seq[i] & ~Qt::KeyboardModifierMask);
	*mod = Qt::KeyboardModifier(seq[i] & Qt::KeyboardModifierMask);
	return hotkey_for(*key, *mod, pckAct->isChecked());
}

bool MainWin::mapIsHotkey(const xJoyMapEntry& ent) {
	if (ent.dev == JMAP_CUT) return true;
	if (ent.dev != JMAP_KEY) return false;
	Qt::Key key;
	Qt::KeyboardModifier mod;
	for (int i = 0; i < ent.seq.count(); i++) {
		if (mapHotkey(ent.seq, i, &key, &mod) >= 0) return true;
	}
	return false;
}

// Presses are dropped while nobody listens: put back what is held. Not
// hotkeys, or the button that has just lifted a pause sets it again.
void MainWin::mapReplayHeld(xGamepad* gp) {
	if (!padLive()) return;
	for (int i = 0; i < gp->mapSize(); i++) {
		xJoyMapEntry ent = gp->mapItem(i);
		if (ent.rps && !mapIsHotkey(ent))
			mapPress(conf.zx, ent);
	}
}

void MainWin::mapKeySeq(const xJoyMapEntry& ent, bool down) {
	Qt::Key key;
	Qt::KeyboardModifier mod;
	for (int i = 0; i < ent.seq.count(); i++) {
		int xkey = mapHotkey(ent.seq, i, &key, &mod);
		if (xkey >= 0) {
			if (down) xkey_press(xkey); else xcut_release(xkey);
			continue;
		}
		static const struct {int mod; int key;} modKeys[] = {
			{Qt::ShiftModifier, XKEY_LSHIFT}, {Qt::ControlModifier, XKEY_LCTRL}, {Qt::AltModifier, XKEY_LALT}
		};
		for (auto& m : modKeys) {
			if (mod & m.mod) {
				if (down) xkey_press(m.key); else xkey_release(m.key);
			}
		}
		xkey = qKey2id(key, mod);
		if (down) xkey_press(xkey); else xkey_release(xkey);
	}
}

void MainWin::mapRelease(Computer* comp, xJoyMapEntry ent) {
	switch(ent.dev) {
		case JMAP_KEY:
			mapKeySeq(ent, false);
			break;
		case JMAP_JOY:
			joyRelease(comp->joy, ent.dir);
			break;
		case JMAP_JOYB:
			joyRelease(comp->joyb, ent.dir);
			break;
		case JMAP_MOUSE:
			mouseRelease(comp->mouse, ent.dir);
			break;
		case JMAP_CUT:
			xcut_release(ent.dir);
			break;
		case JMAP_ZX:
			mapZxKey(comp, ent.dir, false);
			break;
	}
}

// a Spectrum key straight into the machine, past the PC layout
void MainWin::mapZxKey(Computer* comp, int ch, bool down) {
	keyEntry kent = getKeyEntry(ENDKEY);		// the blank one
	memset(kent.zxKey, 0, sizeof(kent.zxKey));
	kent.zxKey[0] = ch;
	if (down) {
		if (comp->hw->keyp) comp->hw->keyp(comp, &kent);
	} else {
		if (comp->hw->keyr) comp->hw->keyr(comp, &kent);
	}
	emit s_keywin_upd(comp->keyb);
}

void MainWin::mapPress(Computer* comp, xJoyMapEntry ent) {
	switch(ent.dev) {
		case JMAP_KEY:
			mapKeySeq(ent, true);
			break;
		case JMAP_JOY:
			joyPress(comp->joy, ent.dir);
			break;
		case JMAP_JOYB:
			joyPress(comp->joyb, ent.dir);
			break;
		case JMAP_MOUSE:
			mousePress(comp->mouse, ent.dir, abs(ent.state / 4096));
			break;
		case JMAP_CUT:
			xkey_press(ent.dir, true);
			break;
		case JMAP_ZX:
			mapZxKey(comp, ent.dir, true);
			break;
	}
}

// A player on the keyboard takes its keys before the layout and the hotkeys
// do, so Ctrl held for fire does not turn the arrows into hotkeys.
bool MainWin::padKey(QKeyEvent* ev, bool down) {
	if (pckAct->isChecked() || conf.zx->flgDBG) return false;
	int id = pad_key_id(ev);
	xGamepad* pads[2] = {conf.gpctrl->gpada, conf.gpctrl->gpadb};
	bool took = false;
	for (xGamepad* gp : pads) {
		if (!gp->bindsKey(id)) continue;
		took = true;
		if (!ev->isAutoRepeat()) mapJoystick(gp, conf.zx, JOY_KEY, id, down ? 1 : 0);
	}
	return took;
}

// TODO: choose gamepad (gpad/gpadb)
void MainWin::mapJoystick(xGamepad* gp, Computer* comp, int type, int num, int st) {
	QList<xJoyMapEntry> presslist = gp->scanMap(type, num, st);
	// what each slot really delivers: the first half of "the pad does
	// nothing" is usually that its map has nothing to say about that button
	if (xlog_on(XLG_INPUT, XLL_DEBUG)) {
		xJoyMapEntry ev;
		ev.type = type;
		ev.num = num;
		ev.state = st;
		xlog_put(XLG_INPUT, XLL_DEBUG, "pad %c: %s -> %i binding(s)",
			(gp == conf.gpctrl->gpada) ? 'A' : 'B',
			xGamepad::getEntryName(ev).toUtf8().data(), (int)presslist.size());
	}
	foreach(const xJoyMapEntry& xjm, presslist)
		mapOut(comp, xjm);
}

// What a binding does to the machine. A release always goes through, so the
// map knows what is held; a press only while the machine has the user's input
// (padLive()), and paused only a hotkey.
void MainWin::mapOut(Computer* comp, const xJoyMapEntry& ent) {
	if (!ent.rps) {
		mapRelease(comp, ent);
	} else if (padLive() && (!conf.emu.pause || mapIsHotkey(ent))) {
		mapPress(comp, ent);
	}
}

// for xGamepad

void MainWin::gpInputChanged(int type, int num, int state) {
	xGamepad* gp = (xGamepad*)sender();
	// an axis reaches the map at full deflection, the way it always did -
	// mouse bindings take their step from the size of it
	if ((type == JOY_AXIS) || (type == JOY_CAXIS))
		state *= 32767;
	mapJoystick(gp, conf.zx, type, num, state);
}

// calling on timer every 20ms

// fps sampling window. Both ends are taken at a frame boundary - the count and
// the time of that same frame - so the reading has no rounding of its own.
struct FpsSample { int frames; qint64 ns; };
static QList<FpsSample> fpsmem;
#define FPS_WINDOW	(1000 / FPS_TICK_MS)	// samples kept: a 1 second window
static int fpsFast = 0;				// the window was taken in fast mode

#if defined(__WIN32) && STICKY_KEY

static struct {
	int vkey;
	int state;
	int qkey;		// Qt::Key
	qint32 nCode;		// nativeScanCode = XKEY_* on windows
} win_mod_tab[6] = {
	{VK_RSHIFT, 0, Qt::Key_Shift, XKEY_RSHIFT},
	{VK_LSHIFT, 0, Qt::Key_Shift, XKEY_LSHIFT},
	{VK_RCONTROL, 0, Qt::Key_Control, XKEY_RCTRL},
	{VK_LCONTROL, 0, Qt::Key_Control, XKEY_LCTRL},
	{VK_RMENU, 0, Qt::Key_Alt, XKEY_RALT},
	{VK_LMENU, 0, Qt::Key_Alt, XKEY_LALT}
};

#endif

void MainWin::timerEvent(QTimerEvent* ev) {
	Computer* comp = conf.zx;
	if (ev->timerId() == secid) {		// 0.2 sec timer, fps counter
		// printf("0.2 sec timer event\n");
		// the rate jumps tenfold into and out of fast mode: start the window
		// over rather than average across the jump
		if (conf.emu.fast != fpsFast) {
			fpsFast = conf.emu.fast;
			fpsmem.clear();
		}
		if (!conf.emu.pause && conf.vid.fctime) {
			FpsSample cur = {conf.vid.fcount, conf.vid.fctime};
			fpsmem.append(cur);
			qint64 dtNs = cur.ns - fpsmem.first().ns;
			int dFrames = cur.frames - fpsmem.first().frames;
			if (dtNs > 0)			// one sample makes no rate yet: keep the last one
				conf.vid.curfps = dFrames * 1e9 / dtNs;
			while (fpsmem.size() > FPS_WINDOW)
				fpsmem.removeFirst();
		} else {
			// no frames are made while paused (emuCycle() itself checks
			// conf.emu.pause), so a stale pre-pause sample would otherwise sit
			// at fpsmem.first() and drag the average down across the whole
			// pause - drop the window instead of letting it slide out one
			// entry at a time after resuming.
			fpsmem.clear();
		}
		if (comp->vid->upd) {
			comp->vid->upd = 0;
			updateWindow();
		}
		updateStatus();
		syncActions();
	} else if (ev->timerId() == cmsid) {	// 1-sec: cmos interrupt
		// TODO: do
	} else if (ev->timerId() == timid) {
// updater
//		if (conf.prof.changed) {
//			comp = conf.zx;
//			conf.prof.changed = 0;
//		}
		if (block) return;
		if (comp->rzx.start) {
			emit s_rzx_start();
		} else if (comp->rzx.stop) {
			emit s_rzx_stop();
		}
		if (comp->rzx.overio) {
			comp->rzx.overio = 0;
			pause(true, PR_RZX);
			shitHappens("RZX playback error");
			emit s_rzx_stop();
			pause(false, PR_RZX);
		}
// turbo, by the time that really went: this timer is a coarse one
		long long now = paceClockNs();
		int ms = (padTurboNs > 0) ? (int)qBound(0LL, (now - padTurboNs) / 1000000, 100LL) : 0;
		padTurboNs = now;
		xGamepad* pads[2] = {conf.gpctrl->gpada, conf.gpctrl->gpadb};
		for (xGamepad* gp : pads) {
			foreach(const xJoyMapEntry& xjm, gp->repTick(ms))
				mapOut(comp, xjm);
		}
// process mouse auto move
		comp->mouse->xpos += comp->mouse->autox;
		comp->mouse->ypos += comp->mouse->autoy;
// if computer sends a message, show it
		if (comp->msg) {
			setMessage(QString(comp->msg));
			comp->msg = NULL;
		}
		watchMedia();
		watchClock();
		watchPads();
		QString vmsg = vrec_message();
		if (!vmsg.isEmpty()) setMessage(vmsg, 4.0);
		switch (vrec_auto_tick()) {
			case VREC_AUTO_STOP: vrec_stop(); break;
			case VREC_AUTO_START: recStart(); break;
		}
// satelites
		updateSatellites();
#if defined(__WIN32) && STICKY_KEY
		if (!conf.emu.pause && isActiveWindow()) {		// if not paused (!)
			int state;
			QKeyEvent* ev;
			// events: nativeScanCode = 0, nativeVirtualKey = XKEY_*
			for (int i = 0; i < 6; i++) {
				state = GetKeyState(win_mod_tab[i].vkey) & 0x8000;
				if (state != win_mod_tab[i].state) {	// state changed
					if (state) {			// press
						ev = new QKeyEvent(QKeyEvent::KeyPress, win_mod_tab[i].qkey, Qt::NoModifier, 0, win_mod_tab[i].nCode, 0);
					} else {			// release
						ev = new QKeyEvent(QKeyEvent::KeyRelease, win_mod_tab[i].qkey, Qt::NoModifier, 0, win_mod_tab[i].nCode, 0);
					}
					QApplication::postEvent(this, ev);
					win_mod_tab[i].state = state;
				}
			}
		}
#endif
	}
}

// if window is not active release keys & buttons, release mouse
void MainWin::focusOutEvent(QFocusEvent*) {
	Computer* comp = conf.zx;
	mouseReleaseAll(comp->mouse);
	unsetCursor();
	if (grabMice) {
		grabMice = 0;
		releaseMouse();
	}
	emit s_keywin_rall(comp->keyb);
	// nor will the keys of a player on the keyboard
	xGamepad* pads[2] = {conf.gpctrl->gpada, conf.gpctrl->gpadb};
	for (xGamepad* gp : pads) {
		if (!gp->isKeyboard()) continue;	// a pad goes on being read, see mapReplayHeld
		foreach(xJoyMapEntry ent, gp->dropHeld())
			mapRelease(comp, ent);
	}
	rewind_want(0);		// their keys will not be seen going up
	xspeed_key(XTM_SLOW, 0);
	xspeed_key(XTM_FFWD, 0);
}

void MainWin::focusInEvent(QFocusEvent*) {
	mapReplayHeld(conf.gpctrl->gpada);
	mapReplayHeld(conf.gpctrl->gpadb);
	if (conf.emu.pause & PR_DEBUG)
		emit s_debug();
	if (grabMice)
		mouseRecenter();
}

// A tool window passes on the hotkeys it has no use of its own for: the F-keys,
// Pause, Scroll Lock and anything with Alt, Ctrl or Cmd. A bare Del, Home or End
// edits or moves there, and Esc closes it.
static bool sat_passes(QKeyEvent* ev) {
	int key = ev->key();
	if ((key >= Qt::Key_F1) && (key <= Qt::Key_F35)) return true;
	if ((key == Qt::Key_Pause) || (key == Qt::Key_ScrollLock)) return true;
	return ev->modifiers() & (Qt::AltModifier | Qt::ControlModifier | Qt::MetaModifier);
}

// On the whole application, since a key goes to whichever widget has the focus
// in a window; an object of its own, so the main window's events pass it once.
class xSatFilter : public QObject {
	public:
		xSatFilter(MainWin* m) : QObject(m), mw(m) {}
		QSet<QWidget*> wins;
	protected:
		bool eventFilter(QObject* obj, QEvent* ev) override {
			if ((ev->type() != QEvent::KeyPress) && (ev->type() != QEvent::KeyRelease)) return false;
			QWidget* wid = qobject_cast<QWidget*>(obj);
			QKeyEvent* kev = static_cast<QKeyEvent*>(ev);
			if (!wid || !sat_passes(kev) || !wins.contains(wid->window())) return false;
			if (QApplication::activeModalWidget() || (mw->hotkeyOf(kev) < 0)) return false;
			if (ev->type() == QEvent::KeyPress) {
				mw->kPress(kev);
			} else {
				mw->kRelease(kev);
			}
			return true;
		}
	private:
		MainWin* mw;
};

// The machine has the user's input: this window is the active one, or a tool
// window of its own is - the gamepads window included, so a pad can be tried
// in the game. Not a dialog, which wants the keys and buttons for itself.
bool MainWin::padLive() {
	if (isActiveWindow()) return true;
	if (QApplication::activeModalWidget() || !satFilter) return false;
	return satFilter->wins.contains(QApplication::activeWindow());
}

void MainWin::addSatellite(QWidget* win) {
	if (!satFilter) {
		satFilter = new xSatFilter(this);
		qApp->installEventFilter(satFilter);
	}
	satFilter->wins.insert(win);
}

// the hotkey a key press means here, -1 for none
int MainWin::hotkeyOf(QKeyEvent* ev) {
	return hotkey_for(hotkey_key(ev), ev->modifiers(), pckAct->isChecked());
}

// what happens to the window happens to the frame
bool MainWin::eventFilter(QObject* obj, QEvent* ev) {
	if (obj == frame) {
		switch (ev->type()) {
			case QEvent::Move:
				// where the window goes back to: fullscreen moves it too
				if (!conf.vid.fullScreen && !frame->isFullScreen()) {
					conf.xpos = frame->pos().x();
					conf.ypos = frame->pos().y();
				}
				emit s_keywin_snap();
				break;
			case QEvent::Close:
				closeEvent(static_cast<QCloseEvent*>(ev));	// accepts or ignores it
				return true;
			default:
				break;
		}
	}
	// the status bar's tape and drives: a click opens their window, the right button their menu
	int drv = -1;
	for (int i = 0; i < 4; i++)
		if (obj == sbDiskBox[i]) drv = i;
	if ((obj == sbTapeBox) || (drv >= 0)) {
		if ((ev->type() == QEvent::MouseButtonPress) && (static_cast<QMouseEvent*>(ev)->button() == Qt::LeftButton)) {
			if (drv < 0) {
				emit s_tape_show();
			} else {
				diskWin->showWindow();
			}
			return true;
		}
		if (ev->type() == QEvent::ContextMenu) {
			QPoint pos = static_cast<QContextMenuEvent*>(ev)->globalPos();
			if (drv < 0) {
				tapeMenu(pos);
			} else {
				fillDrivesMenu();
				if (flpMenu[drv]) flpMenu[drv]->exec(pos);
			}
			setFocus();
			return true;
		}
	}
	return QObject::eventFilter(obj, ev);
}

// a menu does not hold the machine: nothing it does needs it stopped
void MainWin::menuHide() {
	// A submenu closing leaves its parent open, and Favorites is one in the right-click
	// menu: what is still up is asked once it has gone. The line fullscreen grew for the
	// menus goes with the last of them, unless the bar over the picture is still there.
	QTimer::singleShot(0, this, [this]() {
		if (QApplication::activePopupWidget()) return;
		setFocus();
		fsCompose(false);
	});
}


// connection between tape window & tape state

void MainWin::tapStateChanged(int wut, int val) {
	Computer* comp = conf.zx;
	switch(wut) {
		case TW_STATE:
			switch(val) {
				case TWS_PLAY:
					tapUserPlay(comp->tape);
					emit s_tape_upd(comp->tape);
					break;
				case TWS_STOP:
					tapUserStop(comp->tape);
					emit s_tape_upd(comp->tape);
					break;
				case TWS_REC:
					tapRec(comp->tape);
					emit s_tape_upd(comp->tape);
					break;
				case TWS_OPEN:
					pause(true,PR_FILE);
					load_file(comp, NULL, FG_TAPE, -1);
					emit s_tape_upd(comp->tape);
					pause(false,PR_FILE);
					break;
			}
			break;
		case TW_REWIND:
			tapRewind(comp->tape,val);
			emit s_tape_upd(comp->tape);
			break;
		case TW_BREAK:
			comp->tape->blkData[val].breakPoint ^= 1;
			emit s_tape_upd(comp->tape);
			break;
	}
}

// connection between rzx player and emulation state
void MainWin::rzxStateChanged(int state) {
	Computer* comp = conf.zx;
	switch(state) {
		case RWS_PLAY:
			comp->rzx.start = 0;
			pause(false,PR_RZX);
			break;
		case RWS_PAUSE:
			pause(true,PR_RZX);
			break;
		case RWS_STOP:
			rzxStop(comp);
			comp->rzx.stop = 0;
			pause(false,PR_RZX);
			break;
		case RWS_OPEN:
			pause(true,PR_RZX);
			load_file(comp, NULL, FG_RZX, -1);
			if (comp->rzx.play) {
				emit s_rzx_start();
			}
			pause(false,PR_RZX);
			break;
	}
}

// Hand the shown part of the raster to the texture. The rest of the buffer is
// skipped by the unpack settings, so the frame stays whole in memory and can be
// read out again with new bounds - that is what makes a border change take
// effect at once, even while the machine is paused.
void MainWin::uploadFrame() {
#if defined(USEOPENGL) && !BLOCKGL
	Computer* comp = conf.zx;
	Video* vid = comp->vid;
	// GL_UNPACK_ROW_LENGTH and friends are core in GL 3.3 and GLES 3.0, which
	// is what the shaders here ask for anyway ("#version 330" / "300 es"), so
	// a context that has no unpack settings could not draw the picture either
	glPixelStorei(GL_UNPACK_ROW_LENGTH, vid->full.x * 2);
	glPixelStorei(GL_UNPACK_SKIP_PIXELS, vid->lcut.x * 2);
	glPixelStorei(GL_UNPACK_SKIP_ROWS, vid->lcut.y);
	const unsigned char* img = frame_shown_lock();
	glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, vid->vsze.x * 2, vid->vsze.y, 0,
		GL_RGBA, GL_UNSIGNED_BYTE, comp->flgDBG ? scrimg : img);
	frame_shown_unlock();
	glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
	glPixelStorei(GL_UNPACK_SKIP_PIXELS, 0);
	glPixelStorei(GL_UNPACK_SKIP_ROWS, 0);
#endif
}

// Same upload, but from a timer or the emulation thread's frame signal rather
// than from paintEvent, so the context has to be taken first - calling GL
// without it is undefined and crashes some drivers.
void MainWin::uploadOffPaint() {
#if defined(USEOPENGL) && !BLOCKGL
	makeCurrent();
	glBindTexture(GL_TEXTURE_2D, texids[curtex]);
	uploadFrame();
	doneCurrent();
#endif
}

// Redraw now: the one place the picture is drawn (see paintEvent).
void MainWin::presentFrame() {
	blockSignals(true);
	paintOwed = 1;
	repaint();
	blockSignals(false);
}

void MainWin::frame_timer() {
	// No frame yet, so there is nothing in the window - and a window that is
	// never painted is not put on screen at all on macOS. Paint it anyway; no
	// frame is coming meanwhile, so the picture holds still. Autostart is the
	// long case: it runs the machine at full speed and draws no pixels.
	if (!hasPicture) {
		presentFrame();
		return;
	}
	// autostart draws nothing, and what bufimg still holds is the machine from
	// before its reset: the window keeps the picture it had
	if (autostart_busy()) return;
	Computer* comp = conf.zx;
	if (comp) {
		frm_ns += comp->vid->nsPerFrame;
		frm_tmr.setInterval(frm_ns / 1000000);		// 1e6 ns = 1 ms. next frame shot
		frm_ns = frm_ns % 1000000;			// remains
	}
	// In low latency mode d_frame() shows each frame as soon as it is made,
	// so this timer does not paint in normal play (a second timer would beat
	// with frame making and cause a slow frame slip). The timer paints for
	// fast-forward and pause (no frames at 50Hz), and in buffered mode, where
	// a steady timer rate looks smoother.
	if (conf.vid.lowLatency && !conf.emu.fast && !conf.emu.pause) return;
#if defined(USEOPENGL) && !BLOCKGL
	if (conf.emu.fast || conf.emu.pause) {
		// fast loading finishes a picture 30 times a second at most, and one
		// upload of it is enough however often the window is painted
		if (conf.emu.pause || (upSwaps != bufSwaps)) {
			upSwaps = bufSwaps;
			uploadOffPaint();
		}
		queue.clear();
		queue.append(texids[curtex]);
	}
#endif
	presentFrame();
}

void MainWin::d_frame() {
	// before the fast check: a fast load started from the command line makes
	// no frame at normal speed until it is over, and frame_timer() shows
	// nothing without this
	hasPicture = 1;
	if (conf.emu.fast) return;
	upSwaps = -1;		// the texture the timer shows next is not this one
#if defined(USEOPENGL) && !BLOCKGL
	queue.append(texids[curtex]);
	// Low latency keeps only the newest frame; buffered keeps a couple to
	// smooth jitter (see paintEvent).
	if (queue.size() > (conf.vid.lowLatency ? 1 : 2))
		queue.takeFirst();
	uploadOffPaint();
	curtex++;
#endif
	// Low latency: show the frame now. Buffered: let the timer show it.
	if (conf.vid.lowLatency)
		presentFrame();
}

static char numbuf[32];

void MainWin::drawText(QPainter* pnt, int x, int y, const char* buf) {
	size_t len = strlen(buf);
	for (size_t i = 0; i < len; i++) {
		pnt->drawImage(x, y, alphabet, 0, (buf[i] - 32) * 12, 12, 12);
		x += 12;
	}
}

// bug? QOpenGLWidget crash during show->event (ResizeEvent): calling random slot-signal connection
// repaint/update causes recursion on QOpenGLWidget (whyyyyy?) even if there no paintEvent/paingGL
// if paintEvent exists, paintGL do not called

void MainWin::paintEvent(QPaintEvent*) {
#if defined(USEOPENGL) && !BLOCKGL
	// Qt paints the window on its own too - an expose, a menu closing. The
	// framebuffer keeps the last frame for that, and the frame is drawn only
	// when presentFrame() asks. Updates are not switched off instead: Qt then
	// skips this widget when it paints the window, and the window's background
	// stays over the picture.
	// A new framebuffer is the one exception: a size change leaves it empty, and
	// it would show black until the next frame comes.
	if (!paintOwed) return;
	paintOwed = 0;
#endif
	QPainter pnt(this);
#if defined(USEOPENGL) && !BLOCKGL
	pnt.beginNativePainting();
	glClearColor(0, 0, 0, 1);
	glClear(GL_COLOR_BUFFER_BIT);

	// Low latency: take the newest frame and drop the rest for the lowest
	// lag. Buffered: take the oldest (FIFO) so the small buffer smooths jitter.
	if (!queue.isEmpty()) {
		if (conf.vid.lowLatency) {
			curtxid = queue.takeLast();
			queue.clear();
		} else {
			curtxid = queue.takeFirst();
		}
	}

	// The window (or the border) has just changed. Read the frame out of the
	// buffer again with the new bounds instead of stretching the old texture
	// over the new window - and while the machine is paused, no new frame is
	// coming to do it later.
	if (refit && prg.isLinked()) {		// isLinked: initializeGL has run, texids are real
		refit = 0;
		glBindTexture(GL_TEXTURE_2D, texids[curtex]);
		uploadFrame();
		curtxid = texids[curtex];
		queue.clear();
	}

	// curtxid stays 0 until the emulation thread hands over its first frame,
	// and the window is painted before that happens. Binding a texture name
	// that was never generated is undefined - macOS says so out loud, other
	// drivers quietly sample black.
	drawPicture();
	glFlush();
	pnt.endNativePainting();
#else
	// same buffer as the GL path, scaled here instead. No smooth transform, so
	// a dot stays a block of whole pixels.
	Computer* comp = conf.zx;
	Video* vid = comp->vid;
	// cut out under the lock and scaled after it: the emulation waits on it
	const unsigned char* shown = frame_shown_lock();
	QImage img = QImage(comp->flgDBG ? scrimg : shown, vid->full.x * 2, bufSize / bytesPerLine, bytesPerLine, QImage::Format_RGBA8888)
		.copy(vid->lcut.x * 2, vid->lcut.y, vid->vsze.x * 2, vid->vsze.y);
	frame_shown_unlock();
	pnt.drawImage(QRect(drawX, drawY, drawW, drawH), img);
#endif
	drawIcons(pnt);
	pnt.end();
#if defined(USEOPENGL) && !BLOCKGL && !ISLEGACYGL
	if (vrec_wants_screen()) {
		grabScreen();
		// the sign is the user's alone: the picture under it is drawn again
		int rec = recOsd();
		if (rec != osd_none) {
			const qreal r = widgetDpr(this);
			QRect slot = modeSlot();
			QPainter top(this);
			top.beginNativePainting();
			glEnable(GL_SCISSOR_TEST);
			glScissor(int(slot.x() * r), int((height() - slot.bottom() - 1) * r),
				int(slot.width() * r + 1), int(slot.height() * r + 1));
			glClearColor(0, 0, 0, 1);
			glClear(GL_COLOR_BUFFER_BIT);
			drawPicture();
			glDisable(GL_SCISSOR_TEST);
			glFlush();
			top.endNativePainting();
			top.drawImage(slot.topLeft(), osdImg[rec]);
			top.end();
		}
	}
#endif
}

// the frame, through the shader, where drawX/Y/W/H say
void MainWin::drawPicture() {
#if defined(USEOPENGL) && !BLOCKGL
	if (prg.isLinked() && curtxid) {
		const qreal r = widgetDpr(this);
		Computer* comp = conf.zx;
		const GLfloat tex_w = GLfloat(comp->vid->vsze.x * 2);
		const GLfloat tex_h = GLfloat(comp->vid->vsze.y);
		// the quad covers the viewport, and the viewport is the picture: in
		// fullscreen it is a whole-zoom rectangle in the middle of the screen,
		// with the cleared black around it
		glViewport(int(drawX * r + 0.5), int(drawY * r + 0.5),
			int(drawW * r + 0.5), int(drawH * r + 0.5));
		static const QMatrix4x4 legacyMvp = []{
			QMatrix4x4 m;
			m.ortho(0.0f, 1.0f, 1.0f, 0.0f, -1.0f, 1.0f);
			return m;
		}();
		prg.bind();
		prg.setUniformValue("u_tex", 0);
		prg.setUniformValue("rubyTexture", 0);
		prg.setUniformValue("u_mvp_", legacyMvp);
		prg.setUniformValue("rubyInputSize",   tex_w, tex_h);
		prg.setUniformValue("rubyTextureSize", tex_w, tex_h);
		prg.setUniformValue("rubyOutputSize",  GLfloat(drawW * r), GLfloat(drawH * r));

		glActiveTexture(GL_TEXTURE0);
		glBindTexture(GL_TEXTURE_2D, curtxid);

		vao.bind();
		glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
		vao.release();

		prg.release();
	}
#endif
}

// The window as it was just painted, shader and indicators and all. Read
// straight after the paint, while the context is current and the widget's
// framebuffer holds it.
void MainWin::grabScreen() {
#if defined(USEOPENGL) && !BLOCKGL && !ISLEGACYGL
	const qreal r = widgetDpr(this);
	int fw = int(width() * r + 0.5);
	int fh = int(height() * r + 0.5);
	QImage img(fw & ~1, fh & ~1, QImage::Format_RGBA8888);
	glBindFramebuffer(GL_FRAMEBUFFER, defaultFramebufferObject());
	glPixelStorei(GL_PACK_ALIGNMENT, 4);
	glReadPixels(0, fh - img.height(), img.width(), img.height(), GL_RGBA, GL_UNSIGNED_BYTE, img.bits());
	vrec_screen(img);
#endif
}

// A name that says what was on the machine: the image in use, else the machine.
void MainWin::videoRec() {
	vrec_manual();		// the hotkey has the last word over auto recording
	if (vrec_state() == VREC_RUN) {
		vrec_stop();
		setMessage(" video: finishing ");
		return;
	}
	// none yet: offer one, and the next press records
	if (vrec_ffmpeg().isEmpty()) {
		ffmpeg_get(this);
		return;
	}
	recStart();
}

// file: the one the command line names, else the settings' folder and template
bool MainWin::recStart(const QString& file) {
	Computer* comp = conf.zx;
	int sw = 0;
	int sh = 0;
#if defined(USEOPENGL) && !BLOCKGL && !ISLEGACYGL
	if (conf.rec.source == VREC_SRC_SCREEN) {
		const qreal r = widgetDpr(this);
		sw = int(width() * r + 0.5);
		sh = int(height() * r + 0.5);
	}
#endif
	QString err;
	// started, the blinking sign says so: a message would be in the video
	if (vrec_start(comp, media_image_name(), sw, sh, &err, file)) return true;
	setMessage(QString(" video: %0 ").arg(err), 4.0);
	xlog(XLG_VIDEO, XLL_WARN, "recording not started: %s", err.toLocal8Bit().data());
	return false;
}

#define MODE_ICON_W	60	// the pictures are twice this
#define MODE_ICON_TOP	22	// below the fps readout
#define MODE_ICON_TOP_NOFPS	5	// with no fps readout to clear
#define MODE_ICON_RIGHT	5
#define RW_SECS_LINGER	1500	// ms the rewind's seconds stay up after it
#define SIGN_FADE_MS	500	// and any other sign
#define SIGN_FADE_FROM	0.6	// how pale a sign turns as soon as it is over
#define MSG_FADE_FRAMES	25	// the last frames of a message, fading
#define REC_BLINK_MS	500

// where the speed mode and the recording sign go
// the status bar has the rate, when it is there
bool MainWin::fpsOsd() {
	return conf.led.fps && !statusBar->isVisible();
}

QRect MainWin::modeSlot() {
	return QRect(width() - MODE_ICON_W - MODE_ICON_RIGHT, fpsOsd() ? MODE_ICON_TOP : MODE_ICON_TOP_NOFPS,
		MODE_ICON_W, MODE_ICON_W * 3 / 5);
}

// the speed mode, VCR style
int MainWin::speedOsd() {
	if (conf.emu.pause)		// the one place a pause shows
		return osd_pause;
	if (rewind_active())
		return osd_rewind;
	if (conf.emu.fast)
		return osd_fast;
	if (conf.emu.speed != 1.0) {
		int e = ilogb(conf.emu.speed);		// x2 x4 x8 are 1..3, 1/2 1/4 1/8 are -1..-3
		return (e > 0) ? osd_ffwd2 + e - 1 : osd_slow2 - e - 1;
	}
	return osd_none;
}

// the recording sign now: it blinks, and its dark phase gives way to a speed mode
int MainWin::recOsd() {
	if (vrec_state() != VREC_RUN) return osd_none;
	if (!((QDateTime::currentMSecsSinceEpoch() / REC_BLINK_MS) & 1)) return osd_rec;
	return (speedOsd() == osd_none) ? osd_rec_off : osd_none;
}

void MainWin::drawIcons(QPainter& pnt) {
	Computer* comp = conf.zx;
// screenshot
	if (scrCounter > 0) {
		if (scrInterval > 0) {
			scrInterval--;
		} else {
			scrInterval = conf.scrShot.interval;
			scrCounter--;
			screenShot();
		}
	}
// put leds
// keyboard
	// ALF is a ZX with no keyboard at all, so the test is keyp
	if (conf.led.keys && comp->hw->keyp) {
		pnt.drawImage(3, 10, leds[led_kbd]);
		if (~comp->keyb->port & 0x01) pnt.fillRect(3 + 3, 10 + 17, 8, 2, Qt::gray);
		if (~comp->keyb->port & 0x02) pnt.fillRect(3 + 3, 10 + 14, 8, 2, Qt::gray);
		if (~comp->keyb->port & 0x04) pnt.fillRect(3 + 3, 10 + 11, 8, 2, Qt::gray);
		if (~comp->keyb->port & 0x08) pnt.fillRect(3 + 3, 10 + 8, 8, 2, Qt::gray);
		if (~comp->keyb->port & 0x80) pnt.fillRect(3 + 12, 10 + 17, 8, 2, Qt::gray);
		if (~comp->keyb->port & 0x40) pnt.fillRect(3 + 12, 10 + 14, 8, 2, Qt::gray);
		if (~comp->keyb->port & 0x20) pnt.fillRect(3 + 12, 10 + 11, 8, 2, Qt::gray);
		if (~comp->keyb->port & 0x10) pnt.fillRect(3 + 12, 10 + 8, 8, 2, Qt::gray);
	}
	comp->keyb->port = 0xff;
// joystick
	if (comp->joy->used && conf.led.joy) {
		pnt.drawImage(3, 30, leds[led_joy]);
		comp->joy->used = 0;
	}
// mouse
	if (comp->mouse->used) {
		mouseReadAt = paceClockNs();
		if (conf.led.mouse) pnt.drawImage(3, 50, leds[led_mouse]);
		comp->mouse->used = 0;
	}
	// the status bar has these, when it is there
	bool osd = !statusBar->isVisible();
// tape
	if (comp->tape->on && conf.led.tape && osd) {
		pnt.drawImage(3, 70, comp->tape->rec ? leds[led_tap_red] : leds[led_tap_yellow]);
	}
// disc
	// a write reads the sector headers on the way, so it wins over a read, or
	// the led flickers green all through it
	if (conf.led.disk && osd) {
		Floppy* flp = comp->dif->fdc->flp;
		if (flp->wr) {
			pnt.drawImage(3, 90, leds[led_disk_red]);
		} else if (flp->rd) {
			pnt.drawImage(3, 90, leds[led_disk_green]);
		}
	}
	// kept for the status bar, which looks a few times a second
	for (int i = 0; i < 4; i++) {
		Floppy* flp = comp->dif->flp[i];
		flpSeen[i] |= (flp->rd ? 1 : 0) | (flp->wr ? 2 : 0);
		flp->rd = 0;
		flp->wr = 0;
	}
// waveout
	if (conf.snd.wavout) {
		pnt.drawImage(3, 110, leds[led_wav]);
	}
// put the speed mode, VCR style, clear of the fps readout
	int mode = speedOsd();
	// A sign whose state is over fades away rather than blinking out - pale at
	// once, so it does not read as still on. The rewind's stays longer: its
	// seconds under it are there to be read.
	static int signOn = osd_none;
	static int signGone = osd_none;
	static qint64 signGoneAt = 0;
	qint64 now = QDateTime::currentMSecsSinceEpoch();
	if (mode != osd_none) {
		signOn = mode;
		signGone = osd_none;
	} else if (signOn != osd_none) {
		signGone = conf.led.fade ? signOn : osd_none;
		signGoneAt = now;
		signOn = osd_none;
	}
	double fade = 1.0;
	if ((mode == osd_none) && (signGone != osd_none)) {
		int len = (signGone == osd_rewind) ? RW_SECS_LINGER : SIGN_FADE_MS;
		if (now - signGoneAt < len) {
			mode = signGone;
			fade = SIGN_FADE_FROM * (1.0 - double(now - signGoneAt) / len);
		} else {
			signGone = osd_none;
		}
	}
	// recording blinks, taking turns with the speed mode. Recording the window,
	// it is put on after the picture has been read (see paintEvent)
	int rec = recOsd();
	if ((rec != osd_none) && !vrec_wants_screen()) {
		mode = rec;
		fade = 1.0;
	}
	pnt.setOpacity(fade);
	if (mode != osd_none)
		pnt.drawImage(modeSlot().topLeft(), osdImg[mode]);
	// how far back a rewind has gone, under its sign, to the right like it and the
	// same gap below it as to the edge
	if (mode == osd_rewind) {
		int t = rewind_back_tenths();
		sprintf(numbuf, " -%d.%ds ", t / 10, t % 10);
		QRect slot = modeSlot();
		drawText(&pnt, width() - strlen(numbuf) * 12 - MODE_ICON_RIGHT, slot.bottom() + 1 + MODE_ICON_RIGHT, numbuf);
	}
	pnt.setOpacity(1.0);
// put fps
	if (fpsOsd()) {
		sprintf(numbuf, " %.1f ", conf.vid.curfps);
		drawText(&pnt, width() - (strlen(numbuf) * 12) - 5, 5, numbuf);
	}
// put halt counter
	if (conf.led.halt) {
		sprintf(numbuf, " %d : %d ",comp->hCount, comp->fCount);
		drawText(&pnt, width() - strlen(numbuf) * 12 - 8, height() - 20, numbuf);
	}
// put cpu clock, but only when it is not the one the machine ships with: it is
// there to say a run was not on stock timings, and drops to the tick counter's
// line when that is switched off
	double clk = xspeed_clock();
	if (conf.led.clock && (fabs(clk - comp->cpuFrq) > 1e-6)) {
		sprintf(numbuf, " %.6g MHz ", clk);
		drawText(&pnt, width() - strlen(numbuf) * 12 - 8, height() - (conf.led.halt ? 40 : 20), numbuf);
	}
// put messages
	if (msgTimer > 0) {
		if (conf.led.message) {
			if (conf.led.fade && (msgTimer < MSG_FADE_FRAMES))	// its last moments, fading
				pnt.setOpacity(double(msgTimer) / MSG_FADE_FRAMES);
			drawText(&pnt, 5, height() - 20, msg.toLocal8Bit().data());
			pnt.setOpacity(1.0);
		}
		msgTimer--;
	}
// end
}


// A copy, never a move: with shift held the file manager offers a move, and
// would delete the original once the drop is taken.
void MainWin::dragEnterEvent(QDragEnterEvent* ev) {
	if (!ev->mimeData()->hasUrls()) return;
	ev->setDropAction(Qt::CopyAction);
	ev->accept();
}

void MainWin::dropEvent(QDropEvent* ev) {
	if (!ev->mimeData()->hasUrls()) return;
	ev->setDropAction(Qt::CopyAction);
	ev->accept();
	// one drop is one medium: a second file would only land on top of the first
	QString fpath = ev->mimeData()->urls().first().toLocalFile();
	if (fpath.isEmpty()) return;		// something that is not a file here
	frame->raise();
	activateWindow();
#if QT_VERSION >= QT_VERSION_CHECK(6,0,0)
	bool ask = ev->modifiers() & Qt::ShiftModifier;
#else
	bool ask = ev->keyboardModifiers() & Qt::ShiftModifier;
#endif
	if (ask) {
		// not from here: the application the file came from is still waiting
		// for this handler to return, and a menu holds it for as long as it is up
		QTimer::singleShot(0, this, [this, fpath](){dropAsk(fpath);});
	} else {
		openMedia(fpath, FG_ALL, 0, conf.autorun);
	}
}

// shift on a drop or in the open dialog: this one file, run or just mounted.
// 1 run, 0 mount, -1 neither
int MainWin::askRun() {
	QMenu menu(this);
	QAction* run = menu.addAction(QIcon(":/images/play.png"), "Run");
	menu.addAction(QIcon(":/images/cd.png"), "Mount");
	QAction* act = menu.exec(QCursor::pos());
	return act ? ((act == run) ? 1 : 0) : -1;
}

void MainWin::dropAsk(QString path) {
	int run = askRun();
	if (run >= 0) openMedia(path, FG_ALL, 0, run);
}

// One way in for "the user opened a medium", whatever pointed at it: an empty
// path asks the file dialog. The machine the file wants is set up first, then
// it is held while the file is read, and started right there - arming resets
// it anyway, so there is nothing to gain from letting it run a cycle first.
void MainWin::openMedia(const QString& path, int id, int drv, int run) {
	Computer* comp = conf.zx;
	pause(true, PR_FILE);
	QString fpath = path.isEmpty() ? file_ask_open(comp, &id, &drv) : path;
	// Shift held as the dialog is left asks, as it does on a drop
	if (path.isEmpty() && !fpath.isEmpty() && (QGuiApplication::queryKeyboardModifiers() & Qt::ShiftModifier)) {
		run = askRun();
		if (run < 0) fpath.clear();
	}
	std::string mac;
	if (!fpath.isEmpty() && media_machine(comp, fpath, id, drv, run, &mac)) {
		if (!mac.empty()) setMachine(mac);
		QByteArray loc = fpath.toLocal8Bit();
		// the pause does not wait for the cycle, and a snapshot resets the machine
		emu_lock();
		int err = load_file(comp, loc.data(), id, drv);
		emu_unlock();
		if (err == ERR_OK) recent_add(fpath);		// the list is saved with the rest on exit
		media_autorun(comp, run);
	}
	pause(false, PR_FILE);
	checkState();
	emit s_tape_upd(comp->tape);
}


void MainWin::closeEvent(QCloseEvent* ev) {
	pause(true,PR_EXIT);
	Computer* comp = conf.zx;
	if (conf.confexit) {
		if (!areSure("Quit?")) {
			ev->ignore();
			pause(false, PR_EXIT);
			return;
		}
	}
//	std::string fname;
	if (saveChanged()) {
		snd_wav_close();
		vrec_wait();
		frm_tmr.stop();
		killTimer(timid);
		killTimer(secid);
		ideCloseFiles(comp->ide);
		sdcCloseFile(comp->sdc);
		sltEject(comp->slot);		// this must save cartridge ram
		emit s_keywin_close();
		layouts_save();		// their own files, not the settings one
		xm_save_nvram();
		xm_save_over();		// ...and what the user changed on the machine
		saveConfig();
#ifdef USENETWORK
		closeServer();
#endif
		emit s_emulwin_close();
		ev->accept();
	} else {
		ev->ignore();
		pause(false,PR_EXIT);
	}
}

void MainWin::checkState() {
	Computer* comp = conf.zx;
	if (comp->rzx.start) {
		emit s_rzx_start();
	} else if (comp->rzx.stop) {
		emit s_rzx_stop();
	}
		//rzxWin->startPlay();
	//emit s_tape_list(comp->tape);
	//tapeWin->buildList(comp->tape);
	//tapeWin->setCheck(comp->tape->block);
}

// ...

uchar hobHead[] = {'s','c','r','e','e','n',' ',' ','C',0,0,0,0x1b,0,0x1b,0xe7,0x81};	// last 2 bytes is crc

void MainWin::screenShot() {
	Computer* comp = conf.zx;
	int frm = shotFormat[conf.scrShot.format];
	std::string fext;
	switch (frm) {
		case SCR_BMP: fext = "bmp"; break;
		case SCR_PNG: fext = "png"; break;
		case SCR_JPG: fext = "jpg"; break;
		case SCR_SCR: fext = "scr"; break;
		case SCR_HOB: fext = "$C"; break;
	}
	QString fnams = QString(conf.scrShot.dir.c_str()).append(SLASH);
	fnams.append(QString("xpeccy_%0.%1").arg(QTime::currentTime().toString("HHmmss_zzz")).arg(fext.c_str()));
	std::string fnam(fnams.toUtf8().data());
	std::ofstream file;
	Video* vid = comp->vid;
	// the shown frame, taken out of the whole raster. The screen sits in the
	// middle of it, so there is no lopsided border left to trim.
	QImage img(frame_shown_lock(), vid->full.x * 2, bufSize / bytesPerLine, bytesPerLine, QImage::Format_RGBA8888);
	img = img.copy(vid->lcut.x * 2, vid->lcut.y, vid->vsze.x * 2, vid->vsze.y);
	frame_shown_unlock();
	char* sptr = (char*)(comp->mem->ramData + (comp->vid->vidPage << 14));
	switch (frm) {
		case SCR_HOB:
			file.open(fnam.c_str(),std::ios::binary);
			file.write((char*)hobHead,17);
			file.write(sptr, 0x1b00);
			file.close();
			break;
		case SCR_SCR:
			file.open(fnam.c_str(),std::ios::binary);
			file.write(sptr, 0x1b00);
			file.close();
			break;
		case SCR_BMP:
		case SCR_JPG:
		case SCR_PNG:
			if (img.isNull()) break;
			if (conf.scrShot.noBorder)
				img = img.copy((vid->bord.x - vid->lcut.x) * 2, vid->bord.y - vid->lcut.y,
					vid->scrn.x * 2, vid->scrn.y);
			img = img.scaled(img.width() / 2 * conf.vid.scale * comp->hw->xscale,
					img.height() * conf.vid.scale);
			img.save(QString(fnam.c_str()),fext.c_str());
			break;
	}
	setMessage(" screenshot saved ");
}

// video drawing

QList<xLed> leds;

void drawLeds(QPainter& pnt) {
	xLed* led;
	int x,y;
	int i;
	for (i = 0; i < leds.size(); i++) {
		led = &leds[i];
		if (led->showTime > 0) {
			led->showTime--;
			x = led->x;
			y = led->y;
			if (x < 0) x = pnt.device()->width() + x;
			if (y < 0) y = pnt.device()->height() + y;
			pnt.drawImage(x, y, QImage(led->imgName).scaled(16,16));
		}
	}
}

void addLed(int x, int y, QString name, int time) {
	xLed led;
	led.x = x;
	led.y = y;
	led.imgName = name;
	led.showTime = time;
	for (int i = 0; i < leds.size(); i++) {
		if (leds[i].imgName == name) {
			leds[i] = led;
			name.clear();
		}
	}
	if (!name.isEmpty()) {
		leds.append(led);
	}
}

void MainWin::setMessage(QString str, double dur) {
	msgTimer = (int)(dur * 50);
	msg = str;
}

void MainWin::updateSatellites() {
	if (block) return;
	Computer* comp = conf.zx;
// update rzx window
	emit s_rzx_upd(comp);
// update tape window
	emit s_tape_progress(comp->tape);
	// unconditional: the window hides itself when it is not up, and it is what
	// keeps the buttons and the block mark agreeing with the tape however the
	// tape was moved - a rewind from the Tape map page included
	emit s_tape_upd(comp->tape);
	if (comp->tape->blkChange || comp->tape->newBlock) {
		emit s_tape_blk(comp->tape);
		comp->tape->blkChange = 0;
		comp->tape->newBlock = 0;
	}
// update watcher
	emit s_watch_upd(comp);
}

// USER MENU

// Qt never triggers a submenu's own action - a click on the root only opens the
// submenu. This one does both: a root added here runs its action, so the menu
// needs no separate item repeating what the root already says.
// A key ends at the right edge of the menu. The style starts it at the left
// of a column as wide as the widest key, so each item is given a column as
// wide as its own. Qt 5 cannot be told: there the keys stay in one column.
class xMenu : public QMenu {
	public:
		xMenu(QWidget* p = nullptr) : QMenu(p) {}
		xMenu(const QString& title, QWidget* p = nullptr) : QMenu(title, p) {}
	protected:
#if QT_VERSION >= QT_VERSION_CHECK(6,0,0)
		void initStyleOption(QStyleOptionMenuItem* opt, const QAction* act) const override {
			QMenu::initStyleOption(opt, act);
			int tab = opt->text.indexOf('\t');
			if (tab >= 0)
				opt->reservedShortcutWidth = opt->fontMetrics.horizontalAdvance(opt->text.mid(tab + 1));
		}
#endif
};

class xRootMenu : public xMenu {
	public:
		// byPress: opened by a press of the right button, see mouseReleaseEvent
		xRootMenu(QWidget* p = nullptr, bool byPress = true) : xMenu(p), byPress(byPress) {}
		void addRoot(QMenu* sub) {roots.insert(sub->menuAction());}
	protected:
		void showEvent(QShowEvent*) override;
		void mousePressEvent(QMouseEvent*) override;
		void mouseReleaseEvent(QMouseEvent*) override;
		void keyPressEvent(QKeyEvent*) override;
	private:
		bool clickRoot(QAction*);
		QSet<QAction*> roots;
		bool byPress;
		bool pressed = false;
};

bool xRootMenu::clickRoot(QAction* act) {
	if (!roots.contains(act)) return false;
	act->menu()->hide();		// it may already be open under the cursor
	hide();
	act->trigger();
	return true;
}

// MainWin::mousePressEvent pops this menu up on the press of the right button, so
// that button's release lands inside the menu a moment later - and after even a small
// move of the mouse it is on an item, which then fires. Only a release whose press
// this menu saw is a click on it.
void xRootMenu::showEvent(QShowEvent* ev) {
	pressed = false;
	QMenu::showEvent(ev);
}

void xRootMenu::mousePressEvent(QMouseEvent* ev) {
	pressed = true;
	QMenu::mousePressEvent(ev);
}

void xRootMenu::mouseReleaseEvent(QMouseEvent* ev) {
	if (byPress && !pressed) return;
	pressed = false;
#if QT_VERSION >= QT_VERSION_CHECK(6,0,0)
	QPoint pos = ev->position().toPoint();
#else
	QPoint pos = ev->pos();
#endif
	if ((ev->button() == Qt::LeftButton) && clickRoot(actionAt(pos))) return;
	QMenu::mouseReleaseEvent(ev);
}

void xRootMenu::keyPressEvent(QKeyEvent* ev) {
	// Enter on a root does what a click does; Right still opens the submenu
	if (((ev->key() == Qt::Key_Return) || (ev->key() == Qt::Key_Enter)) && clickRoot(activeAction())) return;
	QMenu::keyPressEvent(ev);
}

void MainWin::initUserMenu() {
	xRootMenu* menu = new xRootMenu(this);
	userMenu = menu;
	// the same dialog as the Load hotkey, every kind of image at once
	cutAction(userMenu, "Open...", XCUT_LOAD, "fileopen");
// submenu
	bookmarkMenu = userMenu->addMenu(QIcon(":/images/star.png"),"Favorites");
	userMenu->addSeparator();
	profileMenu = userMenu->addMenu(QIcon(":/images/computer.png"),"Machine");
	turboMenu = userMenu->addMenu(QIcon(":/images/clock.png"),"Turbo mode");
	resMenu = userMenu->addMenu(QIcon(":/images/shutdown.png"),"Reset");
	userMenu->addSeparator();
	keyMenu = userMenu->addMenu(QIcon(":/images/keyboardzx.png"), "Keymap");
	shdMenu = userMenu->addMenu(QIcon(":/images/shader.png"), "Shaders");
	palMenu = userMenu->addMenu(QIcon(":/images/palette.png"), "ZX palette");

	userMenu->addSeparator();
	dskMenu = userMenu->addMenu(QIcon(":/images/fdd_disk.png"), "Disk manager");
	cartMenu = userMenu->addMenu(QIcon(":/images/cartrige.png"), "Cartridge");
	sdcMenu = userMenu->addMenu(QIcon(":/images/sdcard.png"), "SD card");
	hddMenu = userMenu->addMenu(QIcon(":/images/hdd.png"), "Drives");
	diskWin = new xDiskWin(this);
	addSatellite(diskWin);
	diskWin->tapeChanged = [this]() {emit s_tape_upd(conf.zx->tape);};
	diskWin->diskOp = [this](int op, int drv) {diskOp(op, drv);};
	padWin = new xPadWin(this);
	addSatellite(padWin);
	// a model never met before took a slot: say so, and show what it does
	connect(conf.gpctrl, &xGamepadController::newPad, this, [this](int slot) {
		setMessage(QString(" gamepad: player %0 ").arg(slot + 1));
		if (!conf.vid.fullScreen) padWin->showWindow();
	});

	cutAction(userMenu, "Tape player", XCUT_TAPWIN, "tape");
	cutAction(userMenu, "RZX player", XCUT_RZXWIN, "video");
	userMenu->addSeparator();
	pckAct = userMenu->addAction(QIcon(":/images/keyboard.png"),"Grab keyboard");
	pckAct->setCheckable(true);
	// the Profi changes its layout with the grab, so no key may stay down across it
	connect(pckAct, &QAction::toggled, this, [this](bool on) {
		kbdReleaseAll(conf.zx->keyb);
		setMessage(on ? " grab keyboard, " XREL_KEYS " lets go " : " release keyboard ");
	});
	cutActs.append({pckAct, pckAct->text(), XCUT_GRABKBD});	// its key, shown; the action is its own
	cutAction(userMenu, "Virtual keyboard", XCUT_KEYBOARD, "keyboardzx");
	padMenu = userMenu->addMenu(QIcon(":/images/gamepad.png"), "Gamepads");
	// the debugger and its detached panels
	dbgMenu = userMenu->addMenu(QIcon(":/images/bug.png"), "Debugger");
	watchAct = dbgMenu->addAction(QIcon(":/images/objective.png"),"Watcher", this, SIGNAL(s_watch_show()));
	dbgMenu->addAction(QIcon(":/images/rulers.png"),"Screen", this, SIGNAL(s_scr_show()));
	dbgMenu->addAction(QIcon(":/images/note.png"),"Sound chips", this, SIGNAL(s_snd_show()));
	cutAction(userMenu, "Options...", XCUT_OPTIONS, "other");

	connect(profileMenu,SIGNAL(triggered(QAction*)),this,SLOT(profileSelected(QAction*)));
	connect(resMenu,SIGNAL(triggered(QAction*)),this,SLOT(reset(QAction*)));
	connect(shdMenu,SIGNAL(triggered(QAction*)),this,SLOT(shdSelected(QAction*)));
	connect(keyMenu,SIGNAL(triggered(QAction*)),this,SLOT(keySelected(QAction*)));
	connect(palMenu,SIGNAL(triggered(QAction*)),this,SLOT(palSelected(QAction*)));

	// roots that do something of their own, so the submenu needs no item for it
	auto setRoot = [this, menu](QMenu* sub, auto slot) {
		menu->addRoot(sub);
		connect(sub->menuAction(), &QAction::triggered, this, slot);
	};
	setRoot(dbgMenu, &MainWin::doDebug);
	setRoot(bookmarkMenu, &MainWin::favManage);
	setRoot(dskMenu, [this](){diskWin->showWindow();});
	setRoot(padMenu, &MainWin::padWinShow);
	resMenu->menuAction()->setData(RES_DEFAULT);
	setRoot(resMenu, [this](){reset(resMenu->menuAction());});
}

// MENU BAR

#define FS_EDGE 1	// px from the top of the screen that bring up the menu in fullscreen
#define FS_DELAY 150	// ms the pointer has to stay there
#define FS_SETTLE 60	// ms a menu waits for the window to be composed again

// A hotkey as a menu item. The key goes in the text and not in setShortcut:
// a shortcut would take the key before the machine sees it, grabbed or not.
// One action per hotkey, whatever shows it - a menu, the toolbar or both.
QAction* MainWin::cutAct(const QString& name, int id, const QString& icon) {
	QAction* act = cutById.value(id);
	if (act) return act;
	act = new QAction(name, this);
	if (!icon.isEmpty()) act->setIcon(QIcon(":/images/" + icon + ".png"));
	connect(act, &QAction::triggered, this, [this, id]() {
		xkey_press(id, true);
		xcut_release(id);
	});
	cutActs.append({act, name, id});
	cutById[id] = act;
	return act;
}

QAction* MainWin::cutAction(QMenu* menu, const QString& name, int id, const QString& icon) {
	QAction* act = cutAct(name, id, icon);
	menu->addAction(act);
	return act;
}

// once, when an old config had its keys moved to the presets
void MainWin::hotkeysNote() {
	if (!hotkeys_migrated()) return;
	QString key = cutKey(XCUT_HOTKEYS);
	setMessage(key.isEmpty() ? QString(" new hotkeys: see Options ") : QString(" new hotkeys: %0 lists them ").arg(key), 8.0);
}

// a context menu asked for from the keyboard is not one: the menu key is a key
// here like any other, and the menu is on the mouse
void MainWin::contextMenuEvent(QContextMenuEvent* ev) {
	if (ev->reason() == QContextMenuEvent::Keyboard) {
		ev->accept();
	} else {
		ev->ignore();
	}
}

// the keys as they are now, after Options too
// the key a hotkey is on, as the menus write it; empty when it has none
QString MainWin::cutKey(int id) {
	xShortcut* sc = find_shortcut_id(id);
	return (sc && !sc->seq[0].isEmpty()) ? sc->seq[0].toString(QKeySequence::NativeText) : QString();
}

void MainWin::cutTexts() {
	foreach(const xCutAct& cut, cutActs) {
		QString key = cutKey(cut.id);
		QString text = cut.name;
		QString tip = cut.name;
		tip.remove("...");
		if (!key.isEmpty()) {
#ifndef __APPLE__	// Cocoa would make a key equivalent of it, and take the key
			text += "\t" + key;
#endif
			tip += QString(" (%0)").arg(key);
		}
		cut.act->setText(text);
		cut.act->setToolTip(tip);
	}
}

void MainWin::initMenuBar() {
	QMenuBar* bar = frame->menuBar();
	bar->setFocusPolicy(Qt::NoFocus);
	QAction* act;

	fileMenu = new xMenu(this);
	fileMenu->setTitle("File");
	cutAction(fileMenu, "Open...", XCUT_LOAD, "fileopen");
	recentMenu = new xMenu("Recent", this);
	recentMenu->setToolTipsVisible(true);		// the item says the name, the tip where it is
	fileMenu->addMenu(recentMenu);
	cutAction(fileMenu, "Reload", XCUT_RELOAD, "refresh");
	fileMenu->addSeparator();
	cutAction(fileMenu, "Save...", XCUT_SAVE, "save_all");
	cutAction(fileMenu, "Save changed disks", XCUT_FASTSAVE, "floppy");
	cutAction(fileMenu, "Quick save", XCUT_QUICKSAVE);
	cutAction(fileMenu, "Quick load", XCUT_QUICKLOAD);
	cutAction(fileMenu, "Undo quick load", XCUT_QUICKUNDO);
	fileMenu->addSeparator();
	cutAction(fileMenu, "Screenshot", XCUT_SCRSHOT, "grp-screenshot");
	cutAction(fileMenu, "Screenshot series", XCUT_COMBOSHOT);
	recAct = cutAction(fileMenu, "Record video", XCUT_VIDREC, "grp-record");
	recAct->setCheckable(true);
	wavAct = cutAction(fileMenu, "Record sound to WAV...", XCUT_WAV_OUT, "wav");
	wavAct->setCheckable(true);
	fileMenu->addSeparator();
	cutAction(fileMenu, "Options...", XCUT_OPTIONS, "other");
	fileMenu->addSeparator();
#ifdef __WIN32
	act = fileMenu->addAction("Exit\tAlt+F4");
#else
	act = fileMenu->addAction("Exit");
#endif
	act->setMenuRole(QAction::QuitRole);
#ifdef __APPLE__
	act->setShortcut(QKeySequence::Quit);
#endif
	connect(act, &QAction::triggered, frame, &QWidget::close);
	bar->addMenu(fileMenu);
	// its own action: a menu bar shows the icon the right-click menu has, and not the name
	QAction* favAct = new QAction("Favorites", this);
	favAct->setMenu(bookmarkMenu);

	viewMenu = new xMenu("View", this);
	bar->addMenu(viewMenu);
	bar->addAction(favAct);
	sizeMenu = new xMenu("Size", this);
	sizeMenu->setIcon(QIcon(":/images/pixels.png"));
	viewMenu->addMenu(sizeMenu);
	QActionGroup* grp = new QActionGroup(sizeMenu);
	for (int i = 0; i < 6; i++) {
		act = cutAction(sizeMenu, QString("x%0").arg(i + 1), XCUT_SIZEX1 + i);
		act->setCheckable(true);
		grp->addAction(act);
		sizeActs.append(act);
	}
	fullAct = cutAction(viewMenu, "Fullscreen", XCUT_FULLSCR, "grp-picture");
	fullAct->setCheckable(true);
	ratioAct = cutAction(viewMenu, "Keep aspect ratio", XCUT_RATIO, "display");
	ratioAct->setCheckable(true);
	viewMenu->addSeparator();
	viewMenu->addMenu(shdMenu);
	viewMenu->addMenu(palMenu);
	viewMenu->addSeparator();
	tbShowAct = viewMenu->addAction("Toolbar", this, [this](bool on) {
		conf.win.toolbar = on;
		updateWindow();
		saveConfig();
	});
	tbShowAct->setCheckable(true);
	sbShowAct = viewMenu->addAction("Status bar", this, [this](bool on) {
		conf.win.statusbar = on;
		updateWindow();
		saveConfig();
	});
	sbShowAct->setCheckable(true);
	viewMenu->addSeparator();
	cutAction(viewMenu, "Virtual keyboard", XCUT_KEYBOARD, "keyboardzx");

	QMenu* help = new xMenu("Help", this);
	helpMenu = help;
	bar->addMenu(help);
	help->addAction("Project page", this, []() {
		QDesktopServices::openUrl(QUrl("https://github.com/dotkoval/xpeccy-plus"));
	});
	help->addAction("What's new", this, []() {
		QDesktopServices::openUrl(QUrl("https://github.com/dotkoval/xpeccy-plus/blob/main/CHANGELOG.md"));
	});
	help->addAction("Report a problem", this, []() {
		QDesktopServices::openUrl(QUrl("https://github.com/dotkoval/xpeccy-plus/issues"));
	});
	help->addSeparator();
	act = help->addAction("About " XPRODUCT, this, &MainWin::showAbout);
	act->setMenuRole(QAction::AboutRole);

	foreach(QMenu* menu, QList<QMenu*>() << fileMenu << bookmarkMenu << viewMenu << help)
		connect(menu, &QMenu::aboutToHide, this, &MainWin::menuHide);
	connect(fileMenu, &QMenu::aboutToShow, this, &MainWin::syncActions);
	connect(fileMenu, &QMenu::aboutToShow, this, &MainWin::fillRecent);
	connect(viewMenu, &QMenu::aboutToShow, this, &MainWin::syncActions);

	// Fullscreen has no room for the menu bar, so the same menus come up over
	// the picture when the pointer stays at the top edge. Over it and not in
	// the layout: the picture keeps its size and place.
#ifndef __APPLE__	// a mac has its menu at the top of the screen anyway
	fsBar = new QMenuBar(frame);
	fsBar->setFocusPolicy(Qt::NoFocus);
	fsBar->addMenu(fileMenu);
	fsBar->addMenu(viewMenu);
	fsBar->addAction(favAct);
	fsBar->addMenu(help);
	fsBar->hide();
#else
	fsBar = nullptr;
#endif
	fsY = -1;
	fsTall = 0;
	fsShow.setSingleShot(true);
	connect(&fsShow, &QTimer::timeout, this, [this]() {
		if (!conf.vid.fullScreen || grabMice || (fsY > FS_EDGE)) return;	// only passing by
		fsCompose(true);	// before its menus are opened, which they then show over
		fsBar->setGeometry(0, 0, frame->width(), fsBar->sizeHint().height());
		fsBar->raise();
		fsBar->show();
		if (fsTool && conf.win.toolbar) {	// the toolbar comes with it, if there is one in a window
			fsTool->setGeometry(0, fsBar->height(), frame->width(), fsTool->sizeHint().height());
			fsTool->raise();
			fsTool->show();
		}
	});
}

// The picture covers the screen, so it sees every move that is not over the
// bar: one well below it, with no menu of it open, takes the bar away.
void MainWin::fsReveal(int y) {
	fsY = y;
	if (!fsBar || !conf.vid.fullScreen || grabMice) return;
	if (fsBar->isVisible()) {
		int bottom = fsBar->height() + (fsTool->isVisible() ? fsTool->height() : 0);
		if ((y > bottom + FS_EDGE) && !QApplication::activePopupWidget())
			fsHide();
	} else if ((y <= FS_EDGE) && !fsShow.isActive()) {
		fsShow.start(FS_DELAY);
	}
}

void MainWin::fsHide() {
	fsShow.stop();
	if (fsBar && fsBar->isVisible()) {
		fsBar->hide();
		fsTool->hide();
		setFocus();
	}
	fsCompose(false);
}

// A window that covers the monitor exactly is scanned out on its own, past the
// compositor, and a menu opened over it is never drawn. One line taller - off
// the bottom of the screen - it is composed with the rest. With Low latency it
// is made that only while a menu is up, and the switch flashes the screen;
// without, it stays composed, and the compositor's frame of lag is the price.
// on: a menu is about to open. Says whether it changed: the menu waits for the switch.
bool MainWin::fsCompose(bool on) {
#if defined(__WIN32)
	if (!conf.vid.fullScreen) {
		fsTall = 0;
		return false;
	}
	on = fsWantTall(on || fsHeld());
	// The window is asked, not the flag: the system can put a fullscreen
	// window back to the screen's size behind our back, and a menu opened
	// over it then is never drawn - while it holds the mouse and the keys.
	QSize scr = SCREENSIZE;
	bool tall = frame->height() > scr.height();
	if ((on == tall) && (on == bool(fsTall))) return false;
	fsTall = on;
	if (on && (size().height() > scr.height()))
		setFixedSize(scr);		// the same size again would change nothing
	setFixedSize(scr + QSize(0, on ? 1 : 0));
	xlog(XLG_GUI, XLL_INFO, "fullscreen: %s, window was %ix%i", on ? "composed" : "on its own again",
		frame->width(), frame->height());
	return on;
#else
	(void)on;
	return false;
#endif
}

// a window of ours, not a menu or a tip: those are seen to by fsCompose's callers
static bool fs_window(QWidget* w) {
	Qt::WindowType type = w->windowType();
	return (type != Qt::Popup) && (type != Qt::ToolTip);
}

// What has to be seen over the picture: a menu, the bar at the top, or a window
// of ours - the docked keyboard, say, which is otherwise never drawn over one
// scanned out on its own, yet takes the clicks.
bool MainWin::fsHeld() {
	if (QApplication::activePopupWidget() || (fsBar && fsBar->isVisible())) return true;
	QRect scr = frame->geometry();
	foreach(QWidget* w, QApplication::topLevelWidgets()) {
		if ((w == frame) || !w->isVisible() || w->isMinimized() || !fs_window(w)) continue;
		if (w->frameGeometry().intersects(scr)) return true;
	}
	return false;
}

// a window has come, gone or moved
void MainWin::fsOverlay(QWidget* w) {
	if ((w != frame) && fs_window(w)) fsCompose(false);
}

// Back from fullscreen: where the window was, else in the middle - either way
// on a screen, title bar in view. Asked for once the window has its size back.
void MainWin::placeWindow() {
	QScreen* scr = QGuiApplication::screenAt(QPoint(conf.xpos + 40, conf.ypos + 10));
	bool kept = (scr != nullptr);
	if (!scr) scr = frame->screen();
	QRect avail = scr->availableGeometry();
	QRect fg = frame->frameGeometry();
	QPoint at = kept ? QPoint(conf.xpos, conf.ypos) : avail.center() - QPoint(fg.width() / 2, fg.height() / 2);
	at.setX(std::max(avail.left(), std::min(at.x(), avail.right() + 1 - fg.width())));
	at.setY(std::max(avail.top(), std::min(at.y(), avail.bottom() + 1 - fg.height())));
	frame->move(at);
}

void MainWin::popupUserMenu(const QPoint& pos) {
	fillUserMenu();
	auto show = [this, pos]() {
		userMenu->popup(pos);
		userMenu->setFocus();
	};
	if (fsCompose(true)) {
		QTimer::singleShot(FS_SETTLE, this, show);
	} else {
		show();
	}
}

// the images opened last; one that is gone is said so and taken off the list
void MainWin::fillRecent() {
	recentMenu->clear();
	int n = 0;
	foreach(QString path, conf.recentList) {
		n++;
		QString name = QFileInfo(path).fileName().replace("&", "&&");
		QAction* act = recentMenu->addAction(QString("%0  %1").arg(n % 10).arg(name), this, [this, path]() {
			if (!QFileInfo::exists(path)) {
				shitHappens(QString("File not found:<br>%0").arg(path).toLocal8Bit().data());
				recent_remove(path);
				return;
			}
			openMedia(path, FG_ALL, 0, conf.autorun);
			setFocus();
		});
		act->setToolTip(QDir::toNativeSeparators(path));
	}
	if (conf.recentList.isEmpty()) {
		recentMenu->addAction("empty")->setEnabled(false);
	} else {
		recentMenu->addSeparator();
		recentMenu->addAction("Clear", this, []() {conf.recentList.clear();});
	}
}

// not modal: the machine goes on, and a second ask brings the open one forward
void MainWin::showAbout() {
	static QPointer<QMessageBox> box;
	if (box) {
		box->raise();
		box->activateWindow();
		return;
	}
	box = new QMessageBox(this);
	box->setAttribute(Qt::WA_DeleteOnClose);
	box->setModal(false);
	box->setWindowTitle("About " XPRODUCT);
	box->setIconPixmap(frame->windowIcon().pixmap(64, 64));
	box->setTextInteractionFlags(Qt::TextBrowserInteraction);
	// the slogan and the versions in grey: halfway between the text and the ground, so
	// it reads on every style, dark or light
	box->ensurePolished();
	QColor txt = box->palette().color(QPalette::WindowText);
	QColor bgr = box->palette().color(QPalette::Window);
	QString dim = QColor((txt.red() + bgr.red()) / 2, (txt.green() + bgr.green()) / 2, (txt.blue() + bgr.blue()) / 2).name();
	QString dot = QString(" %0 ").arg(QChar(0x00B7));
	box->setText(QString(
		"<span style='font-size:large'><b>" XPRODUCT "</b></span>&nbsp;&nbsp;" XVERSION "<br>"
		"<i style='color:%0'>It really whips the llama's T-states!</i><br><br>"
		"An accurate ZX Spectrum and clones emulator:<br>"
		"comfortable to play on, built to develop with.<br><br>"
		"By Oleksandr \".koval\" Kovalchuk%1MIT license<br>"
		"A fork of <a href=\"https://github.com/samstyle/Xpeccy\">Xpeccy</a> by SAM style<br><br>"
		"<a href=\"https://github.com/dotkoval/xpeccy-plus\">github.com/dotkoval/xpeccy-plus</a><br>"
		"Support the project: <a href=\"https://paypal.me/OKovalchuk\">PayPal</a>%1"
		"<a href=\"https://ko-fi.com/oleksandrkovalkovalchuk25949\">Ko-fi</a><br><br>"
		"Thanks to everyone for the feedback, and especially<br>"
		"to Volutar for regular testing.<br><br>"
		"Includes <a href=\"https://github.com/aaronsgiles/ymfm\">ymfm</a> by Aaron Giles (BSD 3-Clause) and<br>"
		"DejaVu Sans Mono (Bitstream Vera license).<br>"
		"ROM images, icons and FFmpeg keep their own terms: "
		"<a href=\"https://github.com/dotkoval/xpeccy-plus#bundled-roms\">details</a><br><br>"
		"<small style='color:%0'>Qt " QT_VERSION_STR "%1SDL " QT_STRINGIFY(SDL_MAJOR_VERSION) "."
		QT_STRINGIFY(SDL_MINOR_VERSION) "." QT_STRINGIFY(SDL_PATCHLEVEL) "</small>").arg(dim, dot));
	connect(box, &QDialog::finished, this, [this]() {setFocus();});
	box->show();
}

void MainWin::favManage() {
	pause(true, PR_FILE);
	fav_manage(this);
	pause(false, PR_FILE);
	setFocus();
}

// Machine, Media and Debug on the menu bar: what the buttons do, for a window
// with no toolbar, put between Favorites and Help
void MainWin::initMachineMenus() {
	QMenu* mac = new xMenu("Machine", this);
	mac->addMenu(profileMenu);
	mac->addMenu(resMenu);
	mac->addAction(cutById.value(XCUT_NMI));
	mac->addMenu(turboMenu);
	mac->addSeparator();
	mac->addAction(pauseAct);
	mac->addAction(fastAct);
	mac->addAction(slowAct);
	mac->addAction(ffAct);
	// the rewind itself is a key held down, which a menu cannot do; this is whether it may
	QAction* rewOnAct = mac->addAction("Allow rewind", this, [this](bool on) {
		conf.emu.rewind.on = on ? 1 : 0;
		saveConfig();
	});
	rewOnAct->setCheckable(true);
	mac->addSeparator();
	mac->addAction(muteAct);

	QMenu* inp = new xMenu("Input", this);
	inp->addAction(pckAct);
	inp->addAction(mouseAct);
	inp->addMenu(keyMenu);
	inp->addMenu(padMenu);

	QMenu* media = new xMenu("Media", this);
	media->addAction(cutById.value(XCUT_TAPWIN));
	media->addAction(tapeAct);
	media->addAction(tapeRecAct);
	media->addSeparator();
	media->addAction(diskAct);
	// its own action: the drives' list is called Disk manager where its root opens the window
	QAction* drvAct = new QAction(QIcon(":/images/fdd.png"), "Floppy drives", this);
	drvAct->setMenu(dskMenu);
	media->addAction(drvAct);
	QAction* fdcFastAct = media->addAction("Fast disk access", this, [this](bool on) {
		setFlagBit(on, &fdcFlag, FDC_FAST);
		saveConfig();
	});
	fdcFastAct->setCheckable(true);
	media->addSeparator();
	media->addMenu(cartMenu);
	media->addMenu(sdcMenu);
	media->addMenu(hddMenu);
	media->addSeparator();
	media->addAction(cutById.value(XCUT_RZXWIN));

	// one list, not the right-click menu's submenu
	QMenu* dbg = new xMenu("Debug", this);
	dbg->addAction(cutAct("Debugger", XCUT_DEBUG, "bug"));
	dbg->addSeparator();
	dbg->addAction(watchAct);
	dbg->addAction(cutById.value(XCUT_SCRWIN));
	dbg->addAction(cutById.value(XCUT_SNDWIN));

	// their submenus are filled where the right-click menu fills them, before the
	// switches are read: what a drive offers is known only once its list is made
	connect(mac, &QMenu::aboutToShow, this, &MainWin::fillUserMenu);
	connect(inp, &QMenu::aboutToShow, this, &MainWin::fillUserMenu);
	connect(media, &QMenu::aboutToShow, this, &MainWin::fillUserMenu);
	foreach(QMenu* m, QList<QMenu*>() << mac << inp << media << dbg) {
		frame->menuBar()->insertMenu(helpMenu->menuAction(), m);
		if (fsBar) fsBar->insertMenu(helpMenu->menuAction(), m);
		connect(m, &QMenu::aboutToHide, this, &MainWin::menuHide);
		connect(m, &QMenu::aboutToShow, this, &MainWin::syncActions);
	}
	// the switches only these menus have
	connect(mac, &QMenu::aboutToShow, this, [rewOnAct]() {rewOnAct->setChecked(conf.emu.rewind.on);});
	connect(media, &QMenu::aboutToShow, this, [this, drvAct, fdcFastAct]() {
		bool drives = !dskMenu->isEmpty();
		drvAct->setVisible(drives);
		fdcFastAct->setVisible(drives);
		fdcFastAct->setChecked(fdcFlag & FDC_FAST);
	});
}

void MainWin::fillUserMenu() {
	// fill favorites menu: the image in use first, to add it or to take it out
	bookmarkMenu->clear();
	QAction* act;
	QString media = media_current();
	if (!media.isEmpty()) {
		QString name = QFileInfo(media).fileName().replace("&", "&&");
		int idx = findBookmark(media);
		if (idx < 0) {
			bookmarkMenu->addAction(QIcon(":/images/add.png"), QString("Add \"%1\"...").arg(name), this, [this, media]() {
				addFavorite(media);
			});
		} else {
			bookmarkMenu->addAction(QIcon(":/images/cancel.png"), QString("Remove \"%1\"").arg(name), this, [idx]() {
				delBookmark(idx);
				saveConfig();
			});
		}
	}
	bookmarkMenu->addSeparator();		// separators with nothing between them collapse
	foreach(xBookmark bkm, conf.bookmarkList) {
		QString path = QString::fromLocal8Bit(bkm.path.c_str());
		bookmarkMenu->addAction(QString::fromLocal8Bit(bkm.name.c_str()).replace("&", "&&"), this, [this, path]() {
			openMedia(path, FG_ALL, 0, conf.autorun);
			setFocus();
		});
	}
	if (media.isEmpty() && conf.bookmarkList.isEmpty()) {
		act = bookmarkMenu->addAction("empty");
		act->setEnabled(false);
	}
	// the root opens it in the right-click menu, the menu bar has no root
	bookmarkMenu->addSeparator();
	bookmarkMenu->addAction(QIcon(":/images/edit.png"), "Organize...", this, &MainWin::favManage);
	// fill machine menu
	profileMenu->clear();
	std::string family;
	foreach(const xMachine& mac, xm_list()) {
		if (!family.empty() && (mac.family != family))
			profileMenu->addSeparator();
		family = mac.family;
		act = profileMenu->addAction(xm_list_name(mac));
		act->setData(mac.id.c_str());
		act->setCheckable(true);
		act->setChecked(mac.id == conf.macId);
	}
	// fill turbo menu
	turboMenu->clear();
	Computer* comp = conf.zx;
	if (comp) {
		int cur = xm_turbo_index(comp);
		for (int i = 0; i < comp->turboCount; i++) {
			double mhz = comp->cpuFrq * comp->frqMul * comp->turboTab[i];
			act = turboMenu->addAction(QString("x%1 (%2 MHz)").arg(comp->turboTab[i]).arg(mhz, 0, 'g', 6),
				this, [this, i]() {setTurbo(i);});
			act->setCheckable(true);
			act->setChecked(i == cur);
		}
	}
	turboMenu->setEnabled(comp && (comp->turboCount > 1) && !comp->rzx.play);
	fillDrivesMenu();
	// the ROMs a reset can start from on this machine, the default one in bold
	resMenu->clear();
	QList<int> starts = xm_reset_targets();
	foreach(int res, starts) {
		act = resMenu->addAction(xm_reset_name(res));
		act->setData(res);
		if (comp && (res == comp->resbank)) {
			QFont fnt = act->font();
			fnt.setBold(true);
			act->setFont(fnt);
		}
	}
	if (starts.isEmpty()) {
		act = resMenu->addAction("Boots its own firmware");
		act->setEnabled(false);
	}
	fillPadMenu();
	// fill keymaps menu
	keyMenu->clear();
	act = keyMenu->addAction("Default");
	act->setData("");
	act->setCheckable(true);
	if (conf.zx) {
		if (conf.kmapName.empty()) act->setChecked(true);
		foreach(QString str, xres_list("keymaps", QStringList() << "*.map")) {
			act = keyMenu->addAction(str);
			act->setData(str);
			act->setCheckable(true);
			act->setChecked(conf.kmapName == std::string(str.toUtf8().data()));
		}
	}
	// fill shader menu
	shdMenu->clear();
	act = shdMenu->addAction("none");
	act->setData("");
	act->setCheckable(true);
	if (conf.vid.shader.empty()) act->setChecked(true);
#if defined(USEOPENGL) && !BLOCKGL
	if (conf.vid.shd_support) {
		foreach(QString nam, xres_list("shaders", QStringList() << "*.txt")) {
			act = shdMenu->addAction(nam);
			act->setData(nam);
			act->setCheckable(true);
			act->setChecked(nam == conf.vid.shader.c_str());
		}
	}
#endif
	// fill palette menu
	palMenu->clear();
	act = palMenu->addAction(PAL_DEFAULT_NAME);
	act->setData("");
	act->setCheckable(true);
	if (conf.palette.empty()) act->setChecked(true);
	foreach(QString nam, xres_list("palettes", QStringList() << "*.txt")) {
		act = palMenu->addAction(nam);
		act->setData(nam);
		act->setCheckable(true);
		act->setChecked(nam == conf.palette.c_str());
	}
}

// SLOTS

void MainWin::doOptions() {
	pause(true, PR_OPTS);
	emit s_options();
}

// Apply in the options dialog, with the dialog still open. The border size may
// have changed, and the window has to follow it at once - the frame is re-cut
// out of the whole raster, so the picture stays right even though the machine
// is paused and no new frame is coming.
void MainWin::optResize() {
	updateWindow();
	// Apply rebuilds the machine and resets it, and the dialog stays up - so
	// the machine is paused and cannot finish the frame it was drawing. What
	// is in the buffer is half of one frame over half of another, read back
	// with whatever row length the new layout has. Draw a whole one instead.
	if (hasPicture) renderFrame();		// nothing to clean up before the first
	presentFrame();
}

void MainWin::optApply() {
//	relskip = 1;
//	comp = conf.zx;
	Computer* comp = conf.zx;
	fillUserMenu();
	cutTexts();		// Options may have moved a hotkey
	updateWindow();
	loadPalette();
#ifdef USENETWORK
	if (srv.serverPort() != conf.port) {
		closeServer();
		openServer();

	}
#endif
	emit s_tape_upd(comp->tape);
	pause(false, PR_OPTS);
}

void MainWin::doDebug() {
	conf.emu.fast = 0;
	pause(true, PR_DEBUG);
	conf.zx->flgDBG = 1;
	emit s_debug();
}

void MainWin::dbgReturn() {
	pause(false, PR_DEBUG);
	conf.zx->flgDBG = 0;
}

// the name it goes under is asked first, starting from the file's own
void MainWin::addFavorite(const QString& path) {
	pause(true, PR_FILE);
	if (fav_edit(this, -1, path))
		saveConfig();
	pause(false, PR_FILE);
	setFocus();
}

// One frame of the current machine, run from this thread. The image buffer is
// shared by every machine, so after a profile switch it still holds the frame
// the machine before drew - and the emulation may not be in a position to draw
// over it: with the options dialog open it is paused until the dialog closes.
//
// This deliberately steps the cpu rather than asking xThread::emuCycle() for a
// frame: that one is paced, fills the sound buffer and signals the frame on to
// the display, none of which a cosmetic redraw wants, and it stops dead while
// conf.emu.pause is set - which is exactly the case this exists for. emu_lock()
// is what keeps the two apart, the same way the profile switch above uses it.
void MainWin::renderFrame() {
	Computer* comp = conf.zx;
	vid_clear_image();			// whatever is in there was not drawn by this machine
	if (!comp || comp->flgDBG) return;	// the debugger owns the machine, don't step it
	// a frame is some 20000 opcodes. The count is only here to stop a machine
	// that never finishes one - a machine still on "Dummy" hardware, say
	//
	// The ray is wherever the machine was when it stopped, and a reset does
	// not move it, so this takes two runs: the first finishes the frame that
	// was in progress - the lines below the ray and nothing above - and the
	// second draws a whole one from the top. Clearing between them keeps the
	// half-frame out of the picture.
	//
	// vid_set_ray() looks like the shortcut and is not: it puts the ray at
	// the interrupt, which is mid-line, so a frame drawn from there lands in
	// the buffer split and shifted.
	emu_lock();
	for (int i = 0; i < 2; i++) {
		int guard = 1 << 19;
		if (i) vid_clear_image();
		comp->flgFRM = 0;
		while (!comp->flgFRM && !comp->flgBRK && (guard-- > 0))
			// no sound comes of this, but the time passes: the debugger's scope
			// would have a two frame hole in it otherwise
			snd_scope_step(comp, compExec(comp));
	}
	comp->flgFRM = 0;			// the frame is ours, not the pacer's
	// A breakpoint hit inside this one cosmetic frame is dropped on purpose:
	// emuCycle() would only clear the flag without acting on it, and the
	// machine runs into the same breakpoint again as soon as it goes on
	comp->flgBRK = 0;
	frame_publish();
	emu_unlock();
}

void MainWin::onPrfChange() {
	Computer* comp = conf.zx;
	tape_apply_options(comp->tape);
	if (comp->flgFRN) {
		// loadPalette();		// already loaded for each profile
		compReset(comp, RES_DEFAULT);
		comp->flgFRN = 0;
	}
	emit s_keywin_upd(comp->keyb);
	fillUserMenu();		// the turbo steps and the reset starts are the machine's
	vid_upd_scale();
	updateWindow();
	// hasPicture: at start-up there is nothing in the buffer to clean up after,
	// and the machine must not be stepped before the event loop is up
	if (hasPicture) {
		renderFrame();
		presentFrame();
	}
//	saveConfig();
//	emit s_prf_change(conf.prof.cur);
//	conf.prof.changed = 1;
}

void MainWin::profileSelected(QAction* act) {
	setMachine(QString(act->data().toByteArray()).toStdString());
}

// The title names the image the machine is using. A snapshot is in use the
// moment it loads; a tape once it plays, a disk once its drive's motor comes
// on - so what a start puts back in the drives stays out of the title until
// the machine gets to it. A tape or a disk leaves it when it leaves its drive.

void MainWin::showMedia(const QString& path, int src) {
	mediaSrc = src;
	if (path == media_current()) return;
	media_set_current(path);
	vrec_note_image(media_image_name());	// a recording is named after it
	updateHead();
}

// The board switching its own turbo is worth saying, but the machines that do
// it write their configuration port far more often than they change it, so the
// change is noticed here rather than announced from the port handler.
void MainWin::watchClock() {
	Computer* comp = conf.zx;
	if (fabs(comp->hwMul - hwMulSeen) < 1e-6) return;
	hwMulSeen = comp->hwMul;
	// a machine switch resets the turbo and has its own message to show
	if (macSeen != conf.macId) {
		macSeen = conf.macId;
		return;
	}
	setMessage(QString(" %0 MHz (x%1) ").arg(xspeed_clock(), 0, 'g', 6).arg(comp->hwMul));
	xlog(XLG_HW, XLL_INFO, "turbo x%g: CPU at %.2f MHz", comp->hwMul, xspeed_clock());
}

// A pad set to drive the Kempston switches it on, whatever brought that about:
// the pad plugged in, its scheme picked, or a machine switched to.
void MainWin::watchPads() {
	if (xm_pad_kempston())
		setMessage(" Kempston switched on ");
	// what a change to a player's table took from under a held button
	xGamepad* pads[2] = {conf.gpctrl->gpada, conf.gpctrl->gpadb};
	for (xGamepad* gp : pads) {
		foreach(const xJoyMapEntry& ent, gp->takeChanges())
			mapOut(conf.zx, ent);
	}
	// Fire 2..4 come and go with an 8-button Kempston: a machine switch, Options
	int k8 = (conf.zx->joy->type == XJ_KEMPSTON) && conf.zx->joy->extbuttons;
	if (k8 != padK8) {
		padK8 = k8;
		conf.gpctrl->gpada->rebuild();
		conf.gpctrl->gpadb->rebuild();
		padWin->sync();
	}
}

// Gamepads: Manage opens the window, and the first player's joystick can be
// switched right here, mid-game, the way a game's own control menu is answered.
// A second player is rare enough to be set up in the window.
void MainWin::fillPadMenu() {
	padMenu->clear();
	padMenu->addAction(QIcon(":/images/gamepad.png"), "Manage...", this, &MainWin::padWinShow);
	padMenu->addSeparator();
	xGamepad* gp = conf.gpctrl->gpada;
	for (int s = 0; s < GPS_COUNT; s++) {
		QAction* act = padMenu->addAction(pad_scheme_name(s), this, [this, gp, s]() {
			gp->setScheme(s);
			padWin->sync();
			saveConfig();
			setMessage(QString(" joystick: %0 ").arg(pad_scheme_name(s)));
		});
		act->setCheckable(true);
		act->setChecked(gp->scheme() == s);
	}
}

void MainWin::padWinShow() {
	padWin->showWindow();
}

void MainWin::padWinModal() {
	padWin->execOver();
}

void MainWin::watchMedia() {
	Computer* comp = conf.zx;
	QString snap = file_take_snapshot();		// whoever loaded it
	if (!snap.isEmpty())
		showMedia(snap, MEDIA_SNAP);
	// another image in a drive, or none: the name goes if it was this one,
	// and a motor still running from the last one counts as a new start
	for (int src = 0; src <= MEDIA_TAPE; src++) {
		const char* raw = (src == MEDIA_TAPE) ? comp->tape->path : comp->dif->flp[src]->path;
		if (qstrcmp(raw ? raw : "", mediaRaw[src].constData()) == 0) continue;
		mediaRaw[src] = raw;
		mediaSeen &= ~(1 << src);
		if (src == mediaSrc)
			showMedia(QString(), MEDIA_SNAP);
	}
	int seen = comp->tape->on ? (1 << MEDIA_TAPE) : 0;
	for (int i = 0; i < 4; i++) {
		if (comp->dif->flp[i]->motor && comp->dif->flp[i]->insert)
			seen |= 1 << i;
	}
	int rose = seen & ~mediaSeen;
	mediaSeen = seen;
	// flash loading reads the tape without playing it, but it moves it on;
	// updateSatellites() clears the flag later in this same tick
	if (comp->tape->blkChange)
		rose |= 1 << MEDIA_TAPE;
	for (int src = MEDIA_TAPE; src >= 0; src--) {	// the tape first: it plays alone
		if ((rose & (1 << src)) && !mediaRaw[src].isEmpty()) {
			showMedia(QString::fromLocal8Bit(mediaRaw[src]), src);
			break;
		}
	}
}

void MainWin::setMachine(const std::string& id) {
	emu_lock();		// onPrfChange resets the machine, keep it out of the emulation too
	xm_set(id);
	onPrfChange();
	emu_unlock();
}

void MainWin::reset(QAction* act) {
	resetMachine(act->data().toInt());
}

// A reset to one of the ROMs, from a hotkey: a machine that has no such start
// says so and stays as it is
void MainWin::resetTo(int res) {
	if (xm_reset_targets().contains(res)) {
		resetMachine(res);
		return;
	}
	const char* nam = (res == RES_48) ? "48K" : (res == RES_128) ? "128K" : (res == RES_DOS) ? "DOS" : "Service";
	setMessage(QString(" no %0 start here ").arg(nam));
}

// A reset from the running machine's window: one landing mid-opcode lets the opcode
// finish on the new state, and a jump then takes the pc back from the reset.
void MainWin::resetMachine(int res) {
	emit s_rzx_stop();
	emu_lock();		// reset re-inits the hardware
	x_user_reset(conf.zx, res);
	emu_unlock();
}

// the board's own turbo, one of the steps it declares
void MainWin::setTurbo(int idx) {
	Computer* comp = conf.zx;
	if (comp->turboCount < 2) {
		setMessage(" model has no Turbo ");
	} else if (comp->rzx.play) {
		setMessage(" not in RZX ");
	} else {
		emu_lock();		// the new clock re-inits the hardware
		xm_turbo_step(comp, idx);
		emu_unlock();
		setMessage(QString(" %0 MHz (x%1) ").arg(xspeed_clock(), 0, 'g', 6)
			.arg(comp->turboStep));
	}
}


void MainWin::keySelected(QAction* act) {
	QString str = act->data().toString();
	if (str.isEmpty()) {
		conf.kmapName.clear();
	} else {
		conf.kmapName = std::string(str.toUtf8().data());
	}
	saveConfig();
	loadKeys();
}

void MainWin::palSelected(QAction* act) {
	QString str = act->data().toString();
	if (str.isEmpty()) {
		conf.palette.clear();
	} else {
		conf.palette = std::string(str.toUtf8().data());
	}
	saveConfig();
	loadPalette();
}

// debug stufffff


void MainWin::debugAction() {
	sndDebug();
}
